//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace YeahTVApi.Entity
{
    /// <summary>
    /// 模块
    /// </summary>
    public class ModelEntity
    {
        /// <summary>
        /// 模块代码，用来标记是什么模块
        /// </summary>
        public string ModelCode;
        /// <summary>
        /// 显示的比重，用来控制在屏幕上所占的比率，最大值为1，值区间为0.01~1，代表所占的百分比
        /// </summary>
        public double Weight = 0;

        /// <summary>
        /// 动作类型,0代表网页，1代表打开一个Activity，2代表其他
        /// </summary>
        public int? ActionType;

        /// <summary>
        /// 具体的动作，可以是打开URL或者是打开某一个模块
        /// </summary>
        public string Action;

        /// <summary>
        /// 标题,模块在界面上显示的标题，如果不传递该参数则使用客户端默认标题
        /// </summary>
        public string Title;

        /// <summary>
        /// 排序列索引,从0开始
        /// </summary>
        public int ColumnIndex;



        /// <summary>
        /// 标记是否使用网络,0代表不使用，1代表使用。
        /// </summary>
        public int UseNetwork=1;


        /// <summary>
        /// 显示的背景照片,如果该字段有值，则使用该图片替代默认图片
        /// </summary>
        public String BackgroundImageURL;

        /// <summary>
        /// 显示的图标照片,如果该字段有值，则使用该图片替代默认图片
        /// </summary>
        public String IconImageURL;

    }
}
