//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace YeahTVApi.Entity.CentralMapping
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class HotelRoomTypeEx 
    {
        public HotelRoomTypeEx()
        {
            //this.InUse = false;
            //HotelInfo =  new HashSet<HotelInfo>();
        }

        public int ID { get; set; }
        public string HotelID { get; set; }
        public string RoomTypeID { get; set; }
        
        public string BedType { get; set; }
        
        public string BedWidth { get; set; }
        
        public string HotelArea { get; set; }
        
        public string FloorPlace { get; set; }
        
        public string IsHasWindow { get; set; }
        
        public string HasSomkeFree { get; set; }
        
        public string IsADSL { get; set; }
        
        public string IsADSLFee { get; set; }
        
        public string IsADSLWifi { get; set; }
        
        public string MaxCheckInPeoNum { get; set; }
        //public virtual ICollection<HotelInfo> HotelInfo { get; set; }
    }
}
