//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeahTVApi.DomainModel.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YeahTVApi.DomainModel.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 绑定类型 的本地化字符串。
        /// </summary>
        public static string Common_DeviceBingType {
            get {
                return ResourceManager.GetString("Common_DeviceBingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源模板 的本地化字符串。
        /// </summary>
        public static string Common_Display_SourceTemplateName {
            get {
                return ResourceManager.GetString("Common_Display_SourceTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否启用 的本地化字符串。
        /// </summary>
        public static string Common_DisplayActive {
            get {
                return ResourceManager.GetString("Common_DisplayActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        public static string Common_DisplayAddress {
            get {
                return ResourceManager.GetString("Common_DisplayAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AppId 的本地化字符串。
        /// </summary>
        public static string Common_DisplayAppId {
            get {
                return ResourceManager.GetString("Common_DisplayAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否系统应用 的本地化字符串。
        /// </summary>
        public static string Common_DisplayAppIsSystem {
            get {
                return ResourceManager.GetString("Common_DisplayAppIsSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AppKey 的本地化字符串。
        /// </summary>
        public static string Common_DisplayAppKey {
            get {
                return ResourceManager.GetString("Common_DisplayAppKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 APP名称 的本地化字符串。
        /// </summary>
        public static string Common_DisplayAppsName {
            get {
                return ResourceManager.GetString("Common_DisplayAppsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App地址 的本地化字符串。
        /// </summary>
        public static string Common_DisplayAppUrl {
            get {
                return ResourceManager.GetString("Common_DisplayAppUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 APP版本 的本地化字符串。
        /// </summary>
        public static string Common_DisplayAppVersion {
            get {
                return ResourceManager.GetString("Common_DisplayAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 APP版本描述 的本地化字符串。
        /// </summary>
        public static string Common_DisplayAppVersionDescription {
            get {
                return ResourceManager.GetString("Common_DisplayAppVersionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AppId 的本地化字符串。
        /// </summary>
        public static string Common_DisplayBehaviorLogAppId {
            get {
                return ResourceManager.GetString("Common_DisplayBehaviorLogAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志内容 的本地化字符串。
        /// </summary>
        public static string Common_DisplayBehaviorLogBehaviorInfo {
            get {
                return ResourceManager.GetString("Common_DisplayBehaviorLogBehaviorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志详情 的本地化字符串。
        /// </summary>
        public static string Common_DisplayBehaviorLogBehaviorInfoEx {
            get {
                return ResourceManager.GetString("Common_DisplayBehaviorLogBehaviorInfoEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string Common_DisplayBehaviorLogBehaviorType {
            get {
                return ResourceManager.GetString("Common_DisplayBehaviorLogBehaviorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string Common_DisplayBehaviorLogCreateTime {
            get {
                return ResourceManager.GetString("Common_DisplayBehaviorLogCreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 品牌 的本地化字符串。
        /// </summary>
        public static string Common_DisplayBrand {
            get {
                return ResourceManager.GetString("Common_DisplayBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 市 的本地化字符串。
        /// </summary>
        public static string Common_DisplayCity {
            get {
                return ResourceManager.GetString("Common_DisplayCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置描述 的本地化字符串。
        /// </summary>
        public static string Common_DisplayConfigDescribe {
            get {
                return ResourceManager.GetString("Common_DisplayConfigDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置名称 的本地化字符串。
        /// </summary>
        public static string Common_DisplayConfigName {
            get {
                return ResourceManager.GetString("Common_DisplayConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置类型 的本地化字符串。
        /// </summary>
        public static string Common_DisplayConfigType {
            get {
                return ResourceManager.GetString("Common_DisplayConfigType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置值 的本地化字符串。
        /// </summary>
        public static string Common_DisplayConfigValue {
            get {
                return ResourceManager.GetString("Common_DisplayConfigValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点播地址 的本地化字符串。
        /// </summary>
        public static string Common_DisplayCoreSys_VodAddress {
            get {
                return ResourceManager.GetString("Common_DisplayCoreSys_VodAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 广告地址 的本地化字符串。
        /// </summary>
        public static string Common_DisplayCoreSysAdUrl {
            get {
                return ResourceManager.GetString("Common_DisplayCoreSysAdUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动成功自动跳转至首页 的本地化字符串。
        /// </summary>
        public static string Common_DisplayCoreSysAutoToHome {
            get {
                return ResourceManager.GetString("Common_DisplayCoreSysAutoToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 品牌代码 的本地化字符串。
        /// </summary>
        public static string Common_DisplayCoreSysBrandCode {
            get {
                return ResourceManager.GetString("Common_DisplayCoreSysBrandCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 品牌名称 的本地化字符串。
        /// </summary>
        public static string Common_DisplayCoreSysBrandName {
            get {
                return ResourceManager.GetString("Common_DisplayCoreSysBrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码 的本地化字符串。
        /// </summary>
        public static string Common_DisplayCoreSysConfirmPassword {
            get {
                return ResourceManager.GetString("Common_DisplayCoreSysConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 集团代码 的本地化字符串。
        /// </summary>
        public static string Common_DisplayCoreSysGroupCode {
            get {
                return ResourceManager.GetString("Common_DisplayCoreSysGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 集团ID 的本地化字符串。
        /// </summary>
        public static string Common_DisplayCoreSysGroupId {
            get {
                return ResourceManager.GetString("Common_DisplayCoreSysGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 集团名称 的本地化字符串。
        /// </summary>
        public static string Common_DisplayCoreSysGroupName {
            get {
                return ResourceManager.GetString("Common_DisplayCoreSysGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言类型 的本地化字符串。
        /// </summary>
        public static string Common_DisplayCoreSysLanguages {
            get {
                return ResourceManager.GetString("Common_DisplayCoreSysLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎界面背景 的本地化字符串。
        /// </summary>
        public static string Common_DisplayCoreSysLaunchBackground {
            get {
                return ResourceManager.GetString("Common_DisplayCoreSysLaunchBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 酒店PMS地址 的本地化字符串。
        /// </summary>
        public static string Common_DisplayCoreSysLocalPMSUrl {
            get {
                return ResourceManager.GetString("Common_DisplayCoreSysLocalPMSUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录名 的本地化字符串。
        /// </summary>
        public static string Common_DisplayCoreSysLoginName {
            get {
                return ResourceManager.GetString("Common_DisplayCoreSysLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LOGO 的本地化字符串。
        /// </summary>
        public static string Common_DisplayCoreSysLogo {
            get {
                return ResourceManager.GetString("Common_DisplayCoreSysLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 酒店Logo地址 的本地化字符串。
        /// </summary>
        public static string Common_DisplayCoreSysLogoImageUrl {
            get {
                return ResourceManager.GetString("Common_DisplayCoreSysLogoImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string Common_DisplayCoreSysPassword {
            get {
                return ResourceManager.GetString("Common_DisplayCoreSysPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每日价格 的本地化字符串。
        /// </summary>
        public static string Common_DisplayCoreSysPriceOfDay {
            get {
                return ResourceManager.GetString("Common_DisplayCoreSysPriceOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string Common_DisplayCoreSysState {
            get {
                return ResourceManager.GetString("Common_DisplayCoreSysState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板ID 的本地化字符串。
        /// </summary>
        public static string Common_DisplayCoreSysTemplateId {
            get {
                return ResourceManager.GetString("Common_DisplayCoreSysTemplateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string Common_DisplayCoreSysUserName {
            get {
                return ResourceManager.GetString("Common_DisplayCoreSysUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎语 的本地化字符串。
        /// </summary>
        public static string Common_DisplayCoreSysWelcomeWord {
            get {
                return ResourceManager.GetString("Common_DisplayCoreSysWelcomeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区 的本地化字符串。
        /// </summary>
        public static string Common_DisplayCountry {
            get {
                return ResourceManager.GetString("Common_DisplayCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string Common_DisplayCreateTime {
            get {
                return ResourceManager.GetString("Common_DisplayCreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 APP描述 的本地化字符串。
        /// </summary>
        public static string Common_DisplayDescription {
            get {
                return ResourceManager.GetString("Common_DisplayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备密钥 的本地化字符串。
        /// </summary>
        public static string Common_DisplayDeviceKey {
            get {
                return ResourceManager.GetString("Common_DisplayDeviceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备号 的本地化字符串。
        /// </summary>
        public static string Common_DisplayDeviceSeries {
            get {
                return ResourceManager.GetString("Common_DisplayDeviceSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备类型 的本地化字符串。
        /// </summary>
        public static string Common_DisplayDeviceType {
            get {
                return ResourceManager.GetString("Common_DisplayDeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否可编辑 的本地化字符串。
        /// </summary>
        public static string Common_DisplayEditable {
            get {
                return ResourceManager.GetString("Common_DisplayEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string Common_DisplayErpCreateDate {
            get {
                return ResourceManager.GetString("Common_DisplayErpCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱 的本地化字符串。
        /// </summary>
        public static string Common_DisplayErpEmail {
            get {
                return ResourceManager.GetString("Common_DisplayErpEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 集团 的本地化字符串。
        /// </summary>
        public static string Common_DisplayErpGroupId {
            get {
                return ResourceManager.GetString("Common_DisplayErpGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 酒店 的本地化字符串。
        /// </summary>
        public static string Common_DisplayErpHotelId {
            get {
                return ResourceManager.GetString("Common_DisplayErpHotelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新时间 的本地化字符串。
        /// </summary>
        public static string Common_DisplayErpModifyDate {
            get {
                return ResourceManager.GetString("Common_DisplayErpModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系电话 的本地化字符串。
        /// </summary>
        public static string Common_DisplayErpPhone {
            get {
                return ResourceManager.GetString("Common_DisplayErpPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色编号 的本地化字符串。
        /// </summary>
        public static string Common_DisplayErpRoleCode {
            get {
                return ResourceManager.GetString("Common_DisplayErpRoleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        public static string Common_DisplayErpRoleId {
            get {
                return ResourceManager.GetString("Common_DisplayErpRoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色名称 的本地化字符串。
        /// </summary>
        public static string Common_DisplayErpRoleName {
            get {
                return ResourceManager.GetString("Common_DisplayErpRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string Common_DisplayErpState {
            get {
                return ResourceManager.GetString("Common_DisplayErpState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        public static string Common_DisplayErpUserName {
            get {
                return ResourceManager.GetString("Common_DisplayErpUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户类型 的本地化字符串。
        /// </summary>
        public static string Common_DisplayErpUserType {
            get {
                return ResourceManager.GetString("Common_DisplayErpUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App文件名 的本地化字符串。
        /// </summary>
        public static string Common_DisplayFileName {
            get {
                return ResourceManager.GetString("Common_DisplayFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加时间 的本地化字符串。
        /// </summary>
        public static string Common_DisplayFirstVisitTime {
            get {
                return ResourceManager.GetString("Common_DisplayFirstVisitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 集团 的本地化字符串。
        /// </summary>
        public static string Common_DisplayGroupId {
            get {
                return ResourceManager.GetString("Common_DisplayGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 酒店代码 的本地化字符串。
        /// </summary>
        public static string Common_DisplayHotelCode {
            get {
                return ResourceManager.GetString("Common_DisplayHotelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 酒店Id 的本地化字符串。
        /// </summary>
        public static string Common_DisplayHotelId {
            get {
                return ResourceManager.GetString("Common_DisplayHotelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 酒店名称 的本地化字符串。
        /// </summary>
        public static string Common_DisplayHotelName {
            get {
                return ResourceManager.GetString("Common_DisplayHotelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英文名称 的本地化字符串。
        /// </summary>
        public static string Common_DisplayHotelNameEn {
            get {
                return ResourceManager.GetString("Common_DisplayHotelNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支付方式 的本地化字符串。
        /// </summary>
        public static string Common_DisplayHotelPaymentPaymentModels {
            get {
                return ResourceManager.GetString("Common_DisplayHotelPaymentPaymentModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 畅看全场(24小时有效) 的本地化字符串。
        /// </summary>
        public static string Common_DisplayHotelPaymentPayType {
            get {
                return ResourceManager.GetString("Common_DisplayHotelPaymentPayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 畅看价格 的本地化字符串。
        /// </summary>
        public static string Common_DisplayHotelPaymentPriceOfDay {
            get {
                return ResourceManager.GetString("Common_DisplayHotelPaymentPriceOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可置顶影片数 的本地化字符串。
        /// </summary>
        public static string Common_DisplayHotelPaymentTopMoviesCount {
            get {
                return ResourceManager.GetString("Common_DisplayHotelPaymentTopMoviesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Icon地址 的本地化字符串。
        /// </summary>
        public static string Common_DisplayIconUrl {
            get {
                return ResourceManager.GetString("Common_DisplayIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发票抬头 的本地化字符串。
        /// </summary>
        public static string Common_DisplayInvoicesTitle_Name {
            get {
                return ResourceManager.GetString("Common_DisplayInvoicesTitle_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP地址 的本地化字符串。
        /// </summary>
        public static string Common_DisplayIp {
            get {
                return ResourceManager.GetString("Common_DisplayIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否允许子项 的本地化字符串。
        /// </summary>
        public static string Common_DisplayIsAllowChild {
            get {
                return ResourceManager.GetString("Common_DisplayIsAllowChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否子项框架 的本地化字符串。
        /// </summary>
        public static string Common_DisplayIsChildFrame {
            get {
                return ResourceManager.GetString("Common_DisplayIsChildFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否本地PMS 的本地化字符串。
        /// </summary>
        public static string Common_DisplayIsLocalPMS {
            get {
                return ResourceManager.GetString("Common_DisplayIsLocalPMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统应用 的本地化字符串。
        /// </summary>
        public static string Common_DisplayIsSystem {
            get {
                return ResourceManager.GetString("Common_DisplayIsSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转为常用机 的本地化字符串。
        /// </summary>
        public static string Common_DisplayIsUsed {
            get {
                return ResourceManager.GetString("Common_DisplayIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新人 的本地化字符串。
        /// </summary>
        public static string Common_DisplayLastUpdater {
            get {
                return ResourceManager.GetString("Common_DisplayLastUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后更新时间 的本地化字符串。
        /// </summary>
        public static string Common_DisplayLastUpdateTime {
            get {
                return ResourceManager.GetString("Common_DisplayLastUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后更新人 的本地化字符串。
        /// </summary>
        public static string Common_DisplayLastUpdateUser {
            get {
                return ResourceManager.GetString("Common_DisplayLastUpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后更新人 的本地化字符串。
        /// </summary>
        public static string Common_DisplayLastUpdatUser {
            get {
                return ResourceManager.GetString("Common_DisplayLastUpdatUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后更新时间 的本地化字符串。
        /// </summary>
        public static string Common_DisplayLastVisitTime {
            get {
                return ResourceManager.GetString("Common_DisplayLastVisitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纬度 的本地化字符串。
        /// </summary>
        public static string Common_DisplayLatitude {
            get {
                return ResourceManager.GetString("Common_DisplayLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经度 的本地化字符串。
        /// </summary>
        public static string Common_DisplayLongitude {
            get {
                return ResourceManager.GetString("Common_DisplayLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模式 的本地化字符串。
        /// </summary>
        public static string Common_DisplayModel {
            get {
                return ResourceManager.GetString("Common_DisplayModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电影描述 的本地化字符串。
        /// </summary>
        public static string Common_DisplayMovieDescription {
            get {
                return ResourceManager.GetString("Common_DisplayMovieDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电影名 的本地化字符串。
        /// </summary>
        public static string Common_DisplayMovieName {
            get {
                return ResourceManager.GetString("Common_DisplayMovieName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英文电影名 的本地化字符串。
        /// </summary>
        public static string Common_DisplayMovieNameEn {
            get {
                return ResourceManager.GetString("Common_DisplayMovieNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电影简介 的本地化字符串。
        /// </summary>
        public static string Common_DisplayMovieReview {
            get {
                return ResourceManager.GetString("Common_DisplayMovieReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 APP名称 的本地化字符串。
        /// </summary>
        public static string Common_DisplayName {
            get {
                return ResourceManager.GetString("Common_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电影英文名称 的本地化字符串。
        /// </summary>
        public static string Common_DisplayNameEn {
            get {
                return ResourceManager.GetString("Common_DisplayNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string Common_DisplayOrders {
            get {
                return ResourceManager.GetString("Common_DisplayOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包名 的本地化字符串。
        /// </summary>
        public static string Common_DisplayPackageName {
            get {
                return ResourceManager.GetString("Common_DisplayPackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上级节点 的本地化字符串。
        /// </summary>
        public static string Common_DisplayParentId {
            get {
                return ResourceManager.GetString("Common_DisplayParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平台 的本地化字符串。
        /// </summary>
        public static string Common_DisplayPlatfrom {
            get {
                return ResourceManager.GetString("Common_DisplayPlatfrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 省 的本地化字符串。
        /// </summary>
        public static string Common_DisplayProvince {
            get {
                return ResourceManager.GetString("Common_DisplayProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布时间 的本地化字符串。
        /// </summary>
        public static string Common_DisplayPublishDate {
            get {
                return ResourceManager.GetString("Common_DisplayPublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string Common_DisplayRemark {
            get {
                return ResourceManager.GetString("Common_DisplayRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 房间号 的本地化字符串。
        /// </summary>
        public static string Common_DisplayRoomNo {
            get {
                return ResourceManager.GetString("Common_DisplayRoomNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SecureKey 的本地化字符串。
        /// </summary>
        public static string Common_DisplaySecureKey {
            get {
                return ResourceManager.GetString("Common_DisplaySecureKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 送至客房 的本地化字符串。
        /// </summary>
        public static string Common_DisplaySentRoom {
            get {
                return ResourceManager.GetString("Common_DisplaySentRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备号 的本地化字符串。
        /// </summary>
        public static string Common_DisplaySeriseCode {
            get {
                return ResourceManager.GetString("Common_DisplaySeriseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 APP类型 的本地化字符串。
        /// </summary>
        public static string Common_DisplaySystemLogAppType {
            get {
                return ResourceManager.GetString("Common_DisplaySystemLogAppType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string Common_DisplaySystemLogCreateTime {
            get {
                return ResourceManager.GetString("Common_DisplaySystemLogCreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志内容 的本地化字符串。
        /// </summary>
        public static string Common_DisplaySystemLogMessageInfo {
            get {
                return ResourceManager.GetString("Common_DisplaySystemLogMessageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志详情 的本地化字符串。
        /// </summary>
        public static string Common_DisplaySystemLogMessageInfoEx {
            get {
                return ResourceManager.GetString("Common_DisplaySystemLogMessageInfoEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志类型 的本地化字符串。
        /// </summary>
        public static string Common_DisplaySystemLogMessageType {
            get {
                return ResourceManager.GetString("Common_DisplaySystemLogMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电影标签 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTags {
            get {
                return ResourceManager.GetString("Common_DisplayTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTel {
            get {
                return ResourceManager.GetString("Common_DisplayTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模版 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTemplateId {
            get {
                return ResourceManager.GetString("Common_DisplayTemplateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 归属分类 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTemplateType {
            get {
                return ResourceManager.GetString("Common_DisplayTemplateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电影名称 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTitle {
            get {
                return ResourceManager.GetString("Common_DisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 频道类别 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTVChannelCategory {
            get {
                return ResourceManager.GetString("Common_DisplayTVChannelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 频道英文类别 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTVChannelCategoryEn {
            get {
                return ResourceManager.GetString("Common_DisplayTVChannelCategoryEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 频道类别 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTVChannelDefaultCode {
            get {
                return ResourceManager.GetString("Common_DisplayTVChannelDefaultCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电视频道ICon 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTVChannelIcon {
            get {
                return ResourceManager.GetString("Common_DisplayTVChannelIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 频道名称 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTVChannelName {
            get {
                return ResourceManager.GetString("Common_DisplayTVChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英文频道名称 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTVChannelNameEn {
            get {
                return ResourceManager.GetString("Common_DisplayTVChannelNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 节点名称 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTvDocumentElementName {
            get {
                return ResourceManager.GetString("Common_DisplayTvDocumentElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTvDocumentElementOrders {
            get {
                return ResourceManager.GetString("Common_DisplayTvDocumentElementOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上级节店 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTvDocumentElementParentId {
            get {
                return ResourceManager.GetString("Common_DisplayTvDocumentElementParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结构节点ID 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTvDocumentElementTemplateElementId {
            get {
                return ResourceManager.GetString("Common_DisplayTvDocumentElementTemplateElementId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模版ID 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTvDocumentElementTemplateId {
            get {
                return ResourceManager.GetString("Common_DisplayTvDocumentElementTemplateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置编码 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTVHotelConfigConfigCode {
            get {
                return ResourceManager.GetString("Common_DisplayTVHotelConfigConfigCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置名称 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTVHotelConfigConfigName {
            get {
                return ResourceManager.GetString("Common_DisplayTVHotelConfigConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置值 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTVHotelConfigConfigValue {
            get {
                return ResourceManager.GetString("Common_DisplayTVHotelConfigConfigValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTVHotelConfigCreateTime {
            get {
                return ResourceManager.GetString("Common_DisplayTVHotelConfigCreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 酒店名称 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTVHotelConfigHotelId {
            get {
                return ResourceManager.GetString("Common_DisplayTVHotelConfigHotelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后更新人 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTVHotelConfigLastUpdater {
            get {
                return ResourceManager.GetString("Common_DisplayTVHotelConfigLastUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后更新时间 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTVHotelConfigLastUpdateTime {
            get {
                return ResourceManager.GetString("Common_DisplayTVHotelConfigLastUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否可编辑 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTvTemplateAttributeEditable {
            get {
                return ResourceManager.GetString("Common_DisplayTvTemplateAttributeEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTvTemplateCreateDate {
            get {
                return ResourceManager.GetString("Common_DisplayTvTemplateCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建人 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTvTemplateCreateUser {
            get {
                return ResourceManager.GetString("Common_DisplayTvTemplateCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTvTemplateDescription {
            get {
                return ResourceManager.GetString("Common_DisplayTvTemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 节点名称 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTvTemplateElementName {
            get {
                return ResourceManager.GetString("Common_DisplayTvTemplateElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改时间 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTvTemplateModifyDate {
            get {
                return ResourceManager.GetString("Common_DisplayTvTemplateModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改人 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTvTemplateModifyUser {
            get {
                return ResourceManager.GetString("Common_DisplayTvTemplateModifyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板名称 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTvTemplateName {
            get {
                return ResourceManager.GetString("Common_DisplayTvTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模版结构 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTvTemplateTemplateType {
            get {
                return ResourceManager.GetString("Common_DisplayTvTemplateTemplateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTvTemplateTypeDescription {
            get {
                return ResourceManager.GetString("Common_DisplayTvTemplateTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模版名称 的本地化字符串。
        /// </summary>
        public static string Common_DisplayTvTemplateTypeName {
            get {
                return ResourceManager.GetString("Common_DisplayTvTemplateTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户ID 的本地化字符串。
        /// </summary>
        public static string Common_DisplayUserID {
            get {
                return ResourceManager.GetString("Common_DisplayUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 APP版本号 的本地化字符串。
        /// </summary>
        public static string Common_DisplayVersionCode {
            get {
                return ResourceManager.GetString("Common_DisplayVersionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 APP版本名称 的本地化字符串。
        /// </summary>
        public static string Common_DisplayVersionName {
            get {
                return ResourceManager.GetString("Common_DisplayVersionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择所属品牌 的本地化字符串。
        /// </summary>
        public static string Common_ErrorMessageForBrandId {
            get {
                return ResourceManager.GetString("Common_ErrorMessageForBrandId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择所在地区 的本地化字符串。
        /// </summary>
        public static string Common_ErrorMessageForCountry {
            get {
                return ResourceManager.GetString("Common_ErrorMessageForCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入正确的邮箱地址 的本地化字符串。
        /// </summary>
        public static string Common_ErrorMessageForErpEmail {
            get {
                return ResourceManager.GetString("Common_ErrorMessageForErpEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 酒店代码不能为空 的本地化字符串。
        /// </summary>
        public static string Common_ErrorMessageForHotelCode {
            get {
                return ResourceManager.GetString("Common_ErrorMessageForHotelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 酒店名称不能为空 的本地化字符串。
        /// </summary>
        public static string Common_ErrorMessageForHotelName {
            get {
                return ResourceManager.GetString("Common_ErrorMessageForHotelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择模板 的本地化字符串。
        /// </summary>
        public static string Common_ErrorMessageForTemplateId {
            get {
                return ResourceManager.GetString("Common_ErrorMessageForTemplateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入正确的酒店名称 的本地化字符串。
        /// </summary>
        public static string Common_ErrorMessageForTVHotelConfigHotelId {
            get {
                return ResourceManager.GetString("Common_ErrorMessageForTVHotelConfigHotelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地地址 的本地化字符串。
        /// </summary>
        public static string Common_IsLocalFileAddress {
            get {
                return ResourceManager.GetString("Common_IsLocalFileAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询时间 的本地化字符串。
        /// </summary>
        public static string Common_LogCriteria_CurrentTime {
            get {
                return ResourceManager.GetString("Common_LogCriteria_CurrentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本号只能为整数！ 的本地化字符串。
        /// </summary>
        public static string Common_RangeVersionCode {
            get {
                return ResourceManager.GetString("Common_RangeVersionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否启用不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_AppPublish_Active {
            get {
                return ResourceManager.GetString("Required_AppPublish_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App名称不能为空 的本地化字符串。
        /// </summary>
        public static string Required_AppPublish_AppVersion {
            get {
                return ResourceManager.GetString("Required_AppPublish_AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定类型不能为空 的本地化字符串。
        /// </summary>
        public static string Required_AppPublish_BindType {
            get {
                return ResourceManager.GetString("Required_AppPublish_BindType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 酒店名称不能为空 的本地化字符串。
        /// </summary>
        public static string Required_AppPublish_HotelName {
            get {
                return ResourceManager.GetString("Required_AppPublish_HotelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布时间不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_AppPublish_PublishDate {
            get {
                return ResourceManager.GetString("Required_AppPublish_PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备号不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_AppPublish_SeriseCode {
            get {
                return ResourceManager.GetString("Required_AppPublish_SeriseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App版本号为必选项 的本地化字符串。
        /// </summary>
        public static string Required_AppPublish_VersionCode {
            get {
                return ResourceManager.GetString("Required_AppPublish_VersionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否系统应用不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_Apps_IsSystem {
            get {
                return ResourceManager.GetString("Required_Apps_IsSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App名称不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_Apps_Name {
            get {
                return ResourceManager.GetString("Required_Apps_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包名不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_Apps_PackageName {
            get {
                return ResourceManager.GetString("Required_Apps_PackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 APP版本号不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_AppVersion_VersionCode {
            get {
                return ResourceManager.GetString("Required_AppVersion_VersionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 APP版本名称不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_AppVersion_VersionName {
            get {
                return ResourceManager.GetString("Required_AppVersion_VersionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备号不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_AuthUserDeviceTrace_DeviceNo {
            get {
                return ResourceManager.GetString("Required_AuthUserDeviceTrace_DeviceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户ID不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_AuthUserDeviceTrace_UserId {
            get {
                return ResourceManager.GetString("Required_AuthUserDeviceTrace_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备号不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_BackupDevice_DeviceSeries {
            get {
                return ResourceManager.GetString("Required_BackupDevice_DeviceSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 酒店ID不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_BackupDevice_HotelId {
            get {
                return ResourceManager.GetString("Required_BackupDevice_HotelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后更新人不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_BackupDevice_LastUpdatUser {
            get {
                return ResourceManager.GetString("Required_BackupDevice_LastUpdatUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 品牌名称不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_Brand_BrandName {
            get {
                return ResourceManager.GetString("Required_Brand_BrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择集团！ 的本地化字符串。
        /// </summary>
        public static string Required_Brand_GroupId {
            get {
                return ResourceManager.GetString("Required_Brand_GroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择语言！ 的本地化字符串。
        /// </summary>
        public static string Required_CoreSysHotelSencond_Languages {
            get {
                return ResourceManager.GetString("Required_CoreSysHotelSencond_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎界面背景不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_CoreSysHotelSencond_LaunchBackground {
            get {
                return ResourceManager.GetString("Required_CoreSysHotelSencond_LaunchBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 酒店Logo地址不能为空 的本地化字符串。
        /// </summary>
        public static string Required_CoreSysHotelSencond_LogoImageUrl {
            get {
                return ResourceManager.GetString("Required_CoreSysHotelSencond_LogoImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每日价格不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_CoreSysHotelSencond_PriceOfDay {
            get {
                return ResourceManager.GetString("Required_CoreSysHotelSencond_PriceOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎语不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_CoreSysHotelSencond_WelcomeWord {
            get {
                return ResourceManager.GetString("Required_CoreSysHotelSencond_WelcomeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录名不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_CoreSysLogin_LoginName {
            get {
                return ResourceManager.GetString("Required_CoreSysLogin_LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_CoreSysLogin_Password {
            get {
                return ResourceManager.GetString("Required_CoreSysLogin_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_CoreSysLogin_State {
            get {
                return ResourceManager.GetString("Required_CoreSysLogin_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备号不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_DeviceTrace_DeviceSeries {
            get {
                return ResourceManager.GetString("Required_DeviceTrace_DeviceSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 酒店不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_DeviceTrace_HotelId {
            get {
                return ResourceManager.GetString("Required_DeviceTrace_HotelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色代码不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_ErpPowerRole_RoleCode {
            get {
                return ResourceManager.GetString("Required_ErpPowerRole_RoleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色名不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_ErpPowerRole_RoleName {
            get {
                return ResourceManager.GetString("Required_ErpPowerRole_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_ErpSysUser_Email {
            get {
                return ResourceManager.GetString("Required_ErpSysUser_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 集团ID不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_ErpSysUser_GroupId {
            get {
                return ResourceManager.GetString("Required_ErpSysUser_GroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 酒店ID不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_ErpSysUser_HotelId {
            get {
                return ResourceManager.GetString("Required_ErpSysUser_HotelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色ID不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_ErpSysUser_RoleId {
            get {
                return ResourceManager.GetString("Required_ErpSysUser_RoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_ErpSysUser_State {
            get {
                return ResourceManager.GetString("Required_ErpSysUser_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_ErpSysUser_UserName {
            get {
                return ResourceManager.GetString("Required_ErpSysUser_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户类型不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_ErpSysUser_UserType {
            get {
                return ResourceManager.GetString("Required_ErpSysUser_UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电影简介不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_Movie_MovieReview {
            get {
                return ResourceManager.GetString("Required_Movie_MovieReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电影名称不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_Movie_Name {
            get {
                return ResourceManager.GetString("Required_Movie_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板名称不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_MovieTemplate_Title {
            get {
                return ResourceManager.GetString("Required_MovieTemplate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须至少包含 6 个字符 的本地化字符串。
        /// </summary>
        public static string Required_RegisterViewModel_lessChart {
            get {
                return ResourceManager.GetString("Required_RegisterViewModel_lessChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的密码不一致 的本地化字符串。
        /// </summary>
        public static string Required_RegisterViewModel_passwordCompare {
            get {
                return ResourceManager.GetString("Required_RegisterViewModel_passwordCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 频道类别不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_TvChannel_Category {
            get {
                return ResourceManager.GetString("Required_TvChannel_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 频道默认编号不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_TvChannel_DefaultCode {
            get {
                return ResourceManager.GetString("Required_TvChannel_DefaultCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 频道名称不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_TvChannel_Name {
            get {
                return ResourceManager.GetString("Required_TvChannel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置编码不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_TVHotelConfig_ConfigCode {
            get {
                return ResourceManager.GetString("Required_TVHotelConfig_ConfigCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置名称不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_TVHotelConfig_ConfigName {
            get {
                return ResourceManager.GetString("Required_TVHotelConfig_ConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置值不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_TVHotelConfig_ConfigValue {
            get {
                return ResourceManager.GetString("Required_TVHotelConfig_ConfigValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录名长度不能大于16位 的本地化字符串。
        /// </summary>
        public static string Required_TvTemplateType_MaxLoginNameLength {
            get {
                return ResourceManager.GetString("Required_TvTemplateType_MaxLoginNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录名长度不能小于6位 的本地化字符串。
        /// </summary>
        public static string Required_TvTemplateType_MinLoginNameLength {
            get {
                return ResourceManager.GetString("Required_TvTemplateType_MinLoginNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板结构名称不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_TvTemplateType_Name {
            get {
                return ResourceManager.GetString("Required_TvTemplateType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板名称不能为空！ 的本地化字符串。
        /// </summary>
        public static string Required_ViewCopyTemplate_Name {
            get {
                return ResourceManager.GetString("Required_ViewCopyTemplate_Name", resourceCulture);
            }
        }
    }
}
