//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeahTVApi.Resx
{
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Files() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YeahTVApi.Resx.Files", typeof(Files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [{&quot;Code&quot;:&quot;VAP&quot;,&quot;Name&quot;:&quot;北京北&quot;,&quot;ShortName&quot;:&quot;bjb&quot;,&quot;ShortName1&quot;:&quot;bjb&quot;,&quot;FullName&quot;:&quot;beijingbei&quot;},{&quot;Code&quot;:&quot;BOP&quot;,&quot;Name&quot;:&quot;北京东&quot;,&quot;ShortName&quot;:&quot;bjd&quot;,&quot;ShortName1&quot;:&quot;bjd&quot;,&quot;FullName&quot;:&quot;beijingdong&quot;},{&quot;Code&quot;:&quot;BJP&quot;,&quot;Name&quot;:&quot;北京&quot;,&quot;ShortName&quot;:&quot;bji&quot;,&quot;ShortName1&quot;:&quot;bj&quot;,&quot;FullName&quot;:&quot;beijing&quot;},{&quot;Code&quot;:&quot;VNP&quot;,&quot;Name&quot;:&quot;北京南&quot;,&quot;ShortName&quot;:&quot;bjn&quot;,&quot;ShortName1&quot;:&quot;bjn&quot;,&quot;FullName&quot;:&quot;beijingnan&quot;},{&quot;Code&quot;:&quot;BXP&quot;,&quot;Name&quot;:&quot;北京西&quot;,&quot;ShortName&quot;:&quot;bjx&quot;,&quot;ShortName1&quot;:&quot;bjx&quot;,&quot;FullName&quot;:&quot;beijingxi&quot;},{&quot;Code&quot;:&quot;IZQ&quot;,&quot;Name&quot;:&quot;广州南&quot;,&quot;ShortNa... 的本地化字符串。
        /// </summary>
        internal static string StationsJson {
            get {
                return ResourceManager.GetString("StationsJson", resourceCulture);
            }
        }
        
      
        
        /// <summary>
        ///   查找类似 E	0000000000000000000000111111111100000011111111110000001111100000000000111110000011000011111000001100001111100000111000111111111111111111111111111100011111100000110000111110000000000011111111000000001111111111000000111111111111111111111111110000000000000000
        ///3	0000000000000000000000011111111100000001111111110000000111111111000000000000001100000000000000110000000000000111000000011111111101111111111111110111111111111111000000000111111100000111111111000001111111000000000111111110011100000001111111110000000111 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string VcCode1 {
            get {
                return ResourceManager.GetString("VcCode1", resourceCulture);
            }
        }
      
    }
}
