//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeahCenter.RefreshCacheService {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Service : global::System.Configuration.ApplicationSettingsBase {
        
        private static Service defaultInstance = ((Service)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Service())));
        
        public static Service Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.8.69:8099/api/DashBoard")]
        public string RequestUrl {
            get {
                return ((string)(this["RequestUrl"]));
            }
            set {
                this["RequestUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:30:00")]
        public global::System.TimeSpan RunTime {
            get {
                return ((global::System.TimeSpan)(this["RunTime"]));
            }
            set {
                this["RunTime"] = value;
            }
        }
    }
}
