//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace YeahTVApi.Client
{


    /// <summary>
    /// 请求头内容，标准的所有请求都会传递的标准值
    /// </summary>
    public class RequestHeader : RequestHeaderBase
    {
        public String HotelID { get; set; }
        public String RoomNo { get; set; }
       
        /// <summary>
        /// 应用的发放渠道
        /// </summary>
        public string Channel { get; set; }

        /// <summary>
        /// 系统的平台代码，我们会给到固定的数值
        /// </summary>
        public string Platform { get; set; }

        /// <summary>
        /// 客户端网络地址
        /// </summary>
        public string IP { get; set; }

        /// <summary>
        /// 屏幕宽度
        /// </summary>
        public int ScreenWidth { get; set; }

        /// <summary>
        /// 屏幕高度
        /// </summary>
        public int ScreenHeight { get; set; }

        /// <summary>
        /// 屏幕Dpi
        /// </summary>
        public int ScreenDpi { get; set; }

        /// <summary>
        /// 客户端语言
        /// </summary>
        public string Language { get; set; }
    }

    public class RequestHeaderBase
    {
        /// <summary>
        /// 应用识别号
        /// </summary>
        public string APP_ID { get; set; }

        /// <summary>
        /// 设备的序列号
        /// </summary>
        public string DEVNO { get; set; }

        /// <summary>
        /// 设备品牌
        /// </summary>
        public string Brand { get; set; }

        /// <summary>
        /// 设备的制造商
        /// </summary>
        public string Manufacturer { get; set; }

        /// <summary>
        /// 设备型号
        /// </summary>
        public string Model { get; set; }

        /// <summary>
        /// OS版本
        /// </summary>
        public string OSVersion { get; set; }

        /// <summary>
        /// 客户端版本
        /// </summary>
        public string Ver { get; set; }

        public string Token { get; set; }

        public string MacAddress { get; set; }
    }
}