//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HZTVApi.Business.PMSRoomStatusService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomStatusInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RoomStatusInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HZTVApi.Business.PMSRoomStatusService.ArrayOfString AttributeField;
        
        private System.DateTime PlanLeaveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HallIdField;
        
        private System.DateTime ModifyTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public HZTVApi.Business.PMSRoomStatusService.ArrayOfString Attribute {
            get {
                return this.AttributeField;
            }
            set {
                if ((object.ReferenceEquals(this.AttributeField, value) != true)) {
                    this.AttributeField = value;
                    this.RaisePropertyChanged("Attribute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime PlanLeaveDate {
            get {
                return this.PlanLeaveDateField;
            }
            set {
                if ((this.PlanLeaveDateField.Equals(value) != true)) {
                    this.PlanLeaveDateField = value;
                    this.RaisePropertyChanged("PlanLeaveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RoomNumber {
            get {
                return this.RoomNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomNumberField, value) != true)) {
                    this.RoomNumberField = value;
                    this.RaisePropertyChanged("RoomNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string RoomTypeID {
            get {
                return this.RoomTypeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomTypeIDField, value) != true)) {
                    this.RoomTypeIDField = value;
                    this.RaisePropertyChanged("RoomTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string RoomTypeName {
            get {
                return this.RoomTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomTypeNameField, value) != true)) {
                    this.RoomTypeNameField = value;
                    this.RaisePropertyChanged("RoomTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string HallId {
            get {
                return this.HallIdField;
            }
            set {
                if ((object.ReferenceEquals(this.HallIdField, value) != true)) {
                    this.HallIdField = value;
                    this.RaisePropertyChanged("HallId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime ModifyTime {
            get {
                return this.ModifyTimeField;
            }
            set {
                if ((this.ModifyTimeField.Equals(value) != true)) {
                    this.ModifyTimeField = value;
                    this.RaisePropertyChanged("ModifyTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomTypeEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RoomTypeEntity : HZTVApi.Business.PMSRoomStatusService.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomTypeIDField;
        
        private int BedNumField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RoomTypeName {
            get {
                return this.RoomTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomTypeNameField, value) != true)) {
                    this.RoomTypeNameField = value;
                    this.RaisePropertyChanged("RoomTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RoomTypeID {
            get {
                return this.RoomTypeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomTypeIDField, value) != true)) {
                    this.RoomTypeIDField = value;
                    this.RaisePropertyChanged("RoomTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int BedNum {
            get {
                return this.BedNumField;
            }
            set {
                if ((this.BedNumField.Equals(value) != true)) {
                    this.BedNumField = value;
                    this.RaisePropertyChanged("BedNum");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityBase", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HZTVApi.Business.PMSRoomStatusService.RoomTypeEntity))]
    public partial class EntityBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hall", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Hall : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HallIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HallNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HZTVApi.Business.PMSRoomStatusService.Floor[] FloorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string HallID {
            get {
                return this.HallIDField;
            }
            set {
                if ((object.ReferenceEquals(this.HallIDField, value) != true)) {
                    this.HallIDField = value;
                    this.RaisePropertyChanged("HallID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string HallName {
            get {
                return this.HallNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HallNameField, value) != true)) {
                    this.HallNameField = value;
                    this.RaisePropertyChanged("HallName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public HZTVApi.Business.PMSRoomStatusService.Floor[] Floors {
            get {
                return this.FloorsField;
            }
            set {
                if ((object.ReferenceEquals(this.FloorsField, value) != true)) {
                    this.FloorsField = value;
                    this.RaisePropertyChanged("Floors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Floor", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Floor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FloorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FloorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HZTVApi.Business.PMSRoomStatusService.Chamber[] RoomsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoordinateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FloorID {
            get {
                return this.FloorIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FloorIDField, value) != true)) {
                    this.FloorIDField = value;
                    this.RaisePropertyChanged("FloorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FloorName {
            get {
                return this.FloorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FloorNameField, value) != true)) {
                    this.FloorNameField = value;
                    this.RaisePropertyChanged("FloorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public HZTVApi.Business.PMSRoomStatusService.Chamber[] Rooms {
            get {
                return this.RoomsField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomsField, value) != true)) {
                    this.RoomsField = value;
                    this.RaisePropertyChanged("Rooms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Coordinate {
            get {
                return this.CoordinateField;
            }
            set {
                if ((object.ReferenceEquals(this.CoordinateField, value) != true)) {
                    this.CoordinateField = value;
                    this.RaisePropertyChanged("Coordinate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Chamber", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Chamber : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChamberNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChamberTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StoreyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoordinateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HZTVApi.Business.PMSRoomStatusService.RoomTrait[] HobbyCollectionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ChamberNumber {
            get {
                return this.ChamberNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ChamberNumberField, value) != true)) {
                    this.ChamberNumberField = value;
                    this.RaisePropertyChanged("ChamberNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ChamberType {
            get {
                return this.ChamberTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ChamberTypeField, value) != true)) {
                    this.ChamberTypeField = value;
                    this.RaisePropertyChanged("ChamberType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Storey {
            get {
                return this.StoreyField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreyField, value) != true)) {
                    this.StoreyField = value;
                    this.RaisePropertyChanged("Storey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Building {
            get {
                return this.BuildingField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingField, value) != true)) {
                    this.BuildingField = value;
                    this.RaisePropertyChanged("Building");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Coordinate {
            get {
                return this.CoordinateField;
            }
            set {
                if ((object.ReferenceEquals(this.CoordinateField, value) != true)) {
                    this.CoordinateField = value;
                    this.RaisePropertyChanged("Coordinate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public HZTVApi.Business.PMSRoomStatusService.RoomTrait[] HobbyCollection {
            get {
                return this.HobbyCollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.HobbyCollectionField, value) != true)) {
                    this.HobbyCollectionField = value;
                    this.RaisePropertyChanged("HobbyCollection");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomTrait", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RoomTrait : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TraitKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TraitTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TraitKey {
            get {
                return this.TraitKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.TraitKeyField, value) != true)) {
                    this.TraitKeyField = value;
                    this.RaisePropertyChanged("TraitKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TraitText {
            get {
                return this.TraitTextField;
            }
            set {
                if ((object.ReferenceEquals(this.TraitTextField, value) != true)) {
                    this.TraitTextField = value;
                    this.RaisePropertyChanged("TraitText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PMSRoomStatusService.RoomStatusModifySoap")]
    public interface RoomStatusModifySoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsLoginOutRoles", ReplyAction="*")]
        HZTVApi.Business.PMSRoomStatusService.IsLoginOutRolesResponse IsLoginOutRoles(HZTVApi.Business.PMSRoomStatusService.IsLoginOutRolesRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsLoginOutRolesAndEmployee", ReplyAction="*")]
        HZTVApi.Business.PMSRoomStatusService.IsLoginOutRolesAndEmployeeResponse IsLoginOutRolesAndEmployee(HZTVApi.Business.PMSRoomStatusService.IsLoginOutRolesAndEmployeeRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsLogin", ReplyAction="*")]
        HZTVApi.Business.PMSRoomStatusService.IsLoginResponse IsLogin(HZTVApi.Business.PMSRoomStatusService.IsLoginRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsLoginOutEmployee", ReplyAction="*")]
        HZTVApi.Business.PMSRoomStatusService.IsLoginOutEmployeeResponse IsLoginOutEmployee(HZTVApi.Business.PMSRoomStatusService.IsLoginOutEmployeeRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 hotelId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRoomStatusSearchByCondition", ReplyAction="*")]
        HZTVApi.Business.PMSRoomStatusService.GetRoomStatusSearchByConditionResponse GetRoomStatusSearchByCondition(HZTVApi.Business.PMSRoomStatusService.GetRoomStatusSearchByConditionRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 hotelId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetCheckRoom", ReplyAction="*")]
        HZTVApi.Business.PMSRoomStatusService.SetCheckRoomResponse SetCheckRoom(HZTVApi.Business.PMSRoomStatusService.SetCheckRoomRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 hotelId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSystemLogsOfUnApp", ReplyAction="*")]
        HZTVApi.Business.PMSRoomStatusService.GetSystemLogsOfUnAppResponse GetSystemLogsOfUnApp(HZTVApi.Business.PMSRoomStatusService.GetSystemLogsOfUnAppRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 hotelId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetCleanRoom", ReplyAction="*")]
        HZTVApi.Business.PMSRoomStatusService.SetCleanRoomResponse SetCleanRoom(HZTVApi.Business.PMSRoomStatusService.SetCleanRoomRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 hotelId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHotelRoomTypes", ReplyAction="*")]
        HZTVApi.Business.PMSRoomStatusService.GetHotelRoomTypesResponse GetHotelRoomTypes(HZTVApi.Business.PMSRoomStatusService.GetHotelRoomTypesRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 hotelId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHotelInfo", ReplyAction="*")]
        HZTVApi.Business.PMSRoomStatusService.GetHotelInfoResponse GetHotelInfo(HZTVApi.Business.PMSRoomStatusService.GetHotelInfoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 hotelId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetOOORoom", ReplyAction="*")]
        HZTVApi.Business.PMSRoomStatusService.SetOOORoomResponse SetOOORoom(HZTVApi.Business.PMSRoomStatusService.SetOOORoomRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsLoginOutRolesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsLoginOutRoles", Namespace="http://tempuri.org/", Order=0)]
        public HZTVApi.Business.PMSRoomStatusService.IsLoginOutRolesRequestBody Body;
        
        public IsLoginOutRolesRequest() {
        }
        
        public IsLoginOutRolesRequest(HZTVApi.Business.PMSRoomStatusService.IsLoginOutRolesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsLoginOutRolesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passWord;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string hotelId;
        
        public IsLoginOutRolesRequestBody() {
        }
        
        public IsLoginOutRolesRequestBody(string userName, string passWord, string hotelId) {
            this.userName = userName;
            this.passWord = passWord;
            this.hotelId = hotelId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsLoginOutRolesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsLoginOutRolesResponse", Namespace="http://tempuri.org/", Order=0)]
        public HZTVApi.Business.PMSRoomStatusService.IsLoginOutRolesResponseBody Body;
        
        public IsLoginOutRolesResponse() {
        }
        
        public IsLoginOutRolesResponse(HZTVApi.Business.PMSRoomStatusService.IsLoginOutRolesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsLoginOutRolesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsLoginOutRolesResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string employeeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string roles;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string hotelName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int userPermissions;
        
        public IsLoginOutRolesResponseBody() {
        }
        
        public IsLoginOutRolesResponseBody(bool IsLoginOutRolesResult, string employeeName, string roles, string hotelName, int userPermissions) {
            this.IsLoginOutRolesResult = IsLoginOutRolesResult;
            this.employeeName = employeeName;
            this.roles = roles;
            this.hotelName = hotelName;
            this.userPermissions = userPermissions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsLoginOutRolesAndEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsLoginOutRolesAndEmployee", Namespace="http://tempuri.org/", Order=0)]
        public HZTVApi.Business.PMSRoomStatusService.IsLoginOutRolesAndEmployeeRequestBody Body;
        
        public IsLoginOutRolesAndEmployeeRequest() {
        }
        
        public IsLoginOutRolesAndEmployeeRequest(HZTVApi.Business.PMSRoomStatusService.IsLoginOutRolesAndEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsLoginOutRolesAndEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passWord;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string hotelId;
        
        public IsLoginOutRolesAndEmployeeRequestBody() {
        }
        
        public IsLoginOutRolesAndEmployeeRequestBody(string userName, string passWord, string hotelId) {
            this.userName = userName;
            this.passWord = passWord;
            this.hotelId = hotelId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsLoginOutRolesAndEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsLoginOutRolesAndEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public HZTVApi.Business.PMSRoomStatusService.IsLoginOutRolesAndEmployeeResponseBody Body;
        
        public IsLoginOutRolesAndEmployeeResponse() {
        }
        
        public IsLoginOutRolesAndEmployeeResponse(HZTVApi.Business.PMSRoomStatusService.IsLoginOutRolesAndEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsLoginOutRolesAndEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsLoginOutRolesAndEmployeeResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string employeeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string employeeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string roles;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string hotelName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int userPermissions;
        
        public IsLoginOutRolesAndEmployeeResponseBody() {
        }
        
        public IsLoginOutRolesAndEmployeeResponseBody(bool IsLoginOutRolesAndEmployeeResult, string employeeID, string employeeName, string roles, string hotelName, int userPermissions) {
            this.IsLoginOutRolesAndEmployeeResult = IsLoginOutRolesAndEmployeeResult;
            this.employeeID = employeeID;
            this.employeeName = employeeName;
            this.roles = roles;
            this.hotelName = hotelName;
            this.userPermissions = userPermissions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsLogin", Namespace="http://tempuri.org/", Order=0)]
        public HZTVApi.Business.PMSRoomStatusService.IsLoginRequestBody Body;
        
        public IsLoginRequest() {
        }
        
        public IsLoginRequest(HZTVApi.Business.PMSRoomStatusService.IsLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passWord;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string hotelId;
        
        public IsLoginRequestBody() {
        }
        
        public IsLoginRequestBody(string userName, string passWord, string hotelId) {
            this.userName = userName;
            this.passWord = passWord;
            this.hotelId = hotelId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public HZTVApi.Business.PMSRoomStatusService.IsLoginResponseBody Body;
        
        public IsLoginResponse() {
        }
        
        public IsLoginResponse(HZTVApi.Business.PMSRoomStatusService.IsLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsLoginResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string employeeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string hotelName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int userPermissions;
        
        public IsLoginResponseBody() {
        }
        
        public IsLoginResponseBody(bool IsLoginResult, string employeeName, string hotelName, int userPermissions) {
            this.IsLoginResult = IsLoginResult;
            this.employeeName = employeeName;
            this.hotelName = hotelName;
            this.userPermissions = userPermissions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsLoginOutEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsLoginOutEmployee", Namespace="http://tempuri.org/", Order=0)]
        public HZTVApi.Business.PMSRoomStatusService.IsLoginOutEmployeeRequestBody Body;
        
        public IsLoginOutEmployeeRequest() {
        }
        
        public IsLoginOutEmployeeRequest(HZTVApi.Business.PMSRoomStatusService.IsLoginOutEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsLoginOutEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passWord;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string hotelId;
        
        public IsLoginOutEmployeeRequestBody() {
        }
        
        public IsLoginOutEmployeeRequestBody(string userName, string passWord, string hotelId) {
            this.userName = userName;
            this.passWord = passWord;
            this.hotelId = hotelId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsLoginOutEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsLoginOutEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public HZTVApi.Business.PMSRoomStatusService.IsLoginOutEmployeeResponseBody Body;
        
        public IsLoginOutEmployeeResponse() {
        }
        
        public IsLoginOutEmployeeResponse(HZTVApi.Business.PMSRoomStatusService.IsLoginOutEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsLoginOutEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsLoginOutEmployeeResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string employeeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string employeeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string hotelName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int userPermissions;
        
        public IsLoginOutEmployeeResponseBody() {
        }
        
        public IsLoginOutEmployeeResponseBody(bool IsLoginOutEmployeeResult, string employeeID, string employeeName, string hotelName, int userPermissions) {
            this.IsLoginOutEmployeeResult = IsLoginOutEmployeeResult;
            this.employeeID = employeeID;
            this.employeeName = employeeName;
            this.hotelName = hotelName;
            this.userPermissions = userPermissions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRoomStatusSearchByConditionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRoomStatusSearchByCondition", Namespace="http://tempuri.org/", Order=0)]
        public HZTVApi.Business.PMSRoomStatusService.GetRoomStatusSearchByConditionRequestBody Body;
        
        public GetRoomStatusSearchByConditionRequest() {
        }
        
        public GetRoomStatusSearchByConditionRequest(HZTVApi.Business.PMSRoomStatusService.GetRoomStatusSearchByConditionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRoomStatusSearchByConditionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hotelId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string roomStatusList;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string roomTypeList;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string roomFilter;
        
        public GetRoomStatusSearchByConditionRequestBody() {
        }
        
        public GetRoomStatusSearchByConditionRequestBody(string hotelId, string roomStatusList, string roomTypeList, string roomFilter) {
            this.hotelId = hotelId;
            this.roomStatusList = roomStatusList;
            this.roomTypeList = roomTypeList;
            this.roomFilter = roomFilter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRoomStatusSearchByConditionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRoomStatusSearchByConditionResponse", Namespace="http://tempuri.org/", Order=0)]
        public HZTVApi.Business.PMSRoomStatusService.GetRoomStatusSearchByConditionResponseBody Body;
        
        public GetRoomStatusSearchByConditionResponse() {
        }
        
        public GetRoomStatusSearchByConditionResponse(HZTVApi.Business.PMSRoomStatusService.GetRoomStatusSearchByConditionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRoomStatusSearchByConditionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HZTVApi.Business.PMSRoomStatusService.RoomStatusInfo[] GetRoomStatusSearchByConditionResult;
        
        public GetRoomStatusSearchByConditionResponseBody() {
        }
        
        public GetRoomStatusSearchByConditionResponseBody(HZTVApi.Business.PMSRoomStatusService.RoomStatusInfo[] GetRoomStatusSearchByConditionResult) {
            this.GetRoomStatusSearchByConditionResult = GetRoomStatusSearchByConditionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCheckRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetCheckRoom", Namespace="http://tempuri.org/", Order=0)]
        public HZTVApi.Business.PMSRoomStatusService.SetCheckRoomRequestBody Body;
        
        public SetCheckRoomRequest() {
        }
        
        public SetCheckRoomRequest(HZTVApi.Business.PMSRoomStatusService.SetCheckRoomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetCheckRoomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hotelId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string roomId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string operatorId;
        
        public SetCheckRoomRequestBody() {
        }
        
        public SetCheckRoomRequestBody(string hotelId, string roomId, string operatorId) {
            this.hotelId = hotelId;
            this.roomId = roomId;
            this.operatorId = operatorId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCheckRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetCheckRoomResponse", Namespace="http://tempuri.org/", Order=0)]
        public HZTVApi.Business.PMSRoomStatusService.SetCheckRoomResponseBody Body;
        
        public SetCheckRoomResponse() {
        }
        
        public SetCheckRoomResponse(HZTVApi.Business.PMSRoomStatusService.SetCheckRoomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetCheckRoomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetCheckRoomResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg;
        
        public SetCheckRoomResponseBody() {
        }
        
        public SetCheckRoomResponseBody(bool SetCheckRoomResult, string msg) {
            this.SetCheckRoomResult = SetCheckRoomResult;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSystemLogsOfUnAppRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSystemLogsOfUnApp", Namespace="http://tempuri.org/", Order=0)]
        public HZTVApi.Business.PMSRoomStatusService.GetSystemLogsOfUnAppRequestBody Body;
        
        public GetSystemLogsOfUnAppRequest() {
        }
        
        public GetSystemLogsOfUnAppRequest(HZTVApi.Business.PMSRoomStatusService.GetSystemLogsOfUnAppRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSystemLogsOfUnAppRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hotelId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime startDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime endDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int minutes;
        
        public GetSystemLogsOfUnAppRequestBody() {
        }
        
        public GetSystemLogsOfUnAppRequestBody(string hotelId, System.DateTime startDate, System.DateTime endDate, int minutes) {
            this.hotelId = hotelId;
            this.startDate = startDate;
            this.endDate = endDate;
            this.minutes = minutes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSystemLogsOfUnAppResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSystemLogsOfUnAppResponse", Namespace="http://tempuri.org/", Order=0)]
        public HZTVApi.Business.PMSRoomStatusService.GetSystemLogsOfUnAppResponseBody Body;
        
        public GetSystemLogsOfUnAppResponse() {
        }
        
        public GetSystemLogsOfUnAppResponse(HZTVApi.Business.PMSRoomStatusService.GetSystemLogsOfUnAppResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSystemLogsOfUnAppResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetSystemLogsOfUnAppResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errorMsg;
        
        public GetSystemLogsOfUnAppResponseBody() {
        }
        
        public GetSystemLogsOfUnAppResponseBody(byte[] GetSystemLogsOfUnAppResult, string errorMsg) {
            this.GetSystemLogsOfUnAppResult = GetSystemLogsOfUnAppResult;
            this.errorMsg = errorMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCleanRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetCleanRoom", Namespace="http://tempuri.org/", Order=0)]
        public HZTVApi.Business.PMSRoomStatusService.SetCleanRoomRequestBody Body;
        
        public SetCleanRoomRequest() {
        }
        
        public SetCleanRoomRequest(HZTVApi.Business.PMSRoomStatusService.SetCleanRoomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetCleanRoomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hotelId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string roomId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string operatorId;
        
        public SetCleanRoomRequestBody() {
        }
        
        public SetCleanRoomRequestBody(string hotelId, string roomId, string operatorId) {
            this.hotelId = hotelId;
            this.roomId = roomId;
            this.operatorId = operatorId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCleanRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetCleanRoomResponse", Namespace="http://tempuri.org/", Order=0)]
        public HZTVApi.Business.PMSRoomStatusService.SetCleanRoomResponseBody Body;
        
        public SetCleanRoomResponse() {
        }
        
        public SetCleanRoomResponse(HZTVApi.Business.PMSRoomStatusService.SetCleanRoomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetCleanRoomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetCleanRoomResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg;
        
        public SetCleanRoomResponseBody() {
        }
        
        public SetCleanRoomResponseBody(bool SetCleanRoomResult, string msg) {
            this.SetCleanRoomResult = SetCleanRoomResult;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHotelRoomTypesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHotelRoomTypes", Namespace="http://tempuri.org/", Order=0)]
        public HZTVApi.Business.PMSRoomStatusService.GetHotelRoomTypesRequestBody Body;
        
        public GetHotelRoomTypesRequest() {
        }
        
        public GetHotelRoomTypesRequest(HZTVApi.Business.PMSRoomStatusService.GetHotelRoomTypesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHotelRoomTypesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hotelId;
        
        public GetHotelRoomTypesRequestBody() {
        }
        
        public GetHotelRoomTypesRequestBody(string hotelId) {
            this.hotelId = hotelId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHotelRoomTypesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHotelRoomTypesResponse", Namespace="http://tempuri.org/", Order=0)]
        public HZTVApi.Business.PMSRoomStatusService.GetHotelRoomTypesResponseBody Body;
        
        public GetHotelRoomTypesResponse() {
        }
        
        public GetHotelRoomTypesResponse(HZTVApi.Business.PMSRoomStatusService.GetHotelRoomTypesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHotelRoomTypesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HZTVApi.Business.PMSRoomStatusService.RoomTypeEntity[] GetHotelRoomTypesResult;
        
        public GetHotelRoomTypesResponseBody() {
        }
        
        public GetHotelRoomTypesResponseBody(HZTVApi.Business.PMSRoomStatusService.RoomTypeEntity[] GetHotelRoomTypesResult) {
            this.GetHotelRoomTypesResult = GetHotelRoomTypesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHotelInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHotelInfo", Namespace="http://tempuri.org/", Order=0)]
        public HZTVApi.Business.PMSRoomStatusService.GetHotelInfoRequestBody Body;
        
        public GetHotelInfoRequest() {
        }
        
        public GetHotelInfoRequest(HZTVApi.Business.PMSRoomStatusService.GetHotelInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHotelInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hotelId;
        
        public GetHotelInfoRequestBody() {
        }
        
        public GetHotelInfoRequestBody(string hotelId) {
            this.hotelId = hotelId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHotelInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHotelInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public HZTVApi.Business.PMSRoomStatusService.GetHotelInfoResponseBody Body;
        
        public GetHotelInfoResponse() {
        }
        
        public GetHotelInfoResponse(HZTVApi.Business.PMSRoomStatusService.GetHotelInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHotelInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HZTVApi.Business.PMSRoomStatusService.Hall[] GetHotelInfoResult;
        
        public GetHotelInfoResponseBody() {
        }
        
        public GetHotelInfoResponseBody(HZTVApi.Business.PMSRoomStatusService.Hall[] GetHotelInfoResult) {
            this.GetHotelInfoResult = GetHotelInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetOOORoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetOOORoom", Namespace="http://tempuri.org/", Order=0)]
        public HZTVApi.Business.PMSRoomStatusService.SetOOORoomRequestBody Body;
        
        public SetOOORoomRequest() {
        }
        
        public SetOOORoomRequest(HZTVApi.Business.PMSRoomStatusService.SetOOORoomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetOOORoomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hotelId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string roomId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime beginDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime endDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string reason;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string operatorId;
        
        public SetOOORoomRequestBody() {
        }
        
        public SetOOORoomRequestBody(string hotelId, string roomId, System.DateTime beginDate, System.DateTime endDate, string reason, string operatorId) {
            this.hotelId = hotelId;
            this.roomId = roomId;
            this.beginDate = beginDate;
            this.endDate = endDate;
            this.reason = reason;
            this.operatorId = operatorId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetOOORoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetOOORoomResponse", Namespace="http://tempuri.org/", Order=0)]
        public HZTVApi.Business.PMSRoomStatusService.SetOOORoomResponseBody Body;
        
        public SetOOORoomResponse() {
        }
        
        public SetOOORoomResponse(HZTVApi.Business.PMSRoomStatusService.SetOOORoomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetOOORoomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetOOORoomResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg;
        
        public SetOOORoomResponseBody() {
        }
        
        public SetOOORoomResponseBody(bool SetOOORoomResult, string msg) {
            this.SetOOORoomResult = SetOOORoomResult;
            this.msg = msg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RoomStatusModifySoapChannel : HZTVApi.Business.PMSRoomStatusService.RoomStatusModifySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoomStatusModifySoapClient : System.ServiceModel.ClientBase<HZTVApi.Business.PMSRoomStatusService.RoomStatusModifySoap>, HZTVApi.Business.PMSRoomStatusService.RoomStatusModifySoap {
        
        public RoomStatusModifySoapClient() {
        }
        
        public RoomStatusModifySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoomStatusModifySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomStatusModifySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomStatusModifySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HZTVApi.Business.PMSRoomStatusService.IsLoginOutRolesResponse HZTVApi.Business.PMSRoomStatusService.RoomStatusModifySoap.IsLoginOutRoles(HZTVApi.Business.PMSRoomStatusService.IsLoginOutRolesRequest request) {
            return base.Channel.IsLoginOutRoles(request);
        }
        
        public bool IsLoginOutRoles(string userName, string passWord, string hotelId, out string employeeName, out string roles, out string hotelName, out int userPermissions) {
            HZTVApi.Business.PMSRoomStatusService.IsLoginOutRolesRequest inValue = new HZTVApi.Business.PMSRoomStatusService.IsLoginOutRolesRequest();
            inValue.Body = new HZTVApi.Business.PMSRoomStatusService.IsLoginOutRolesRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.passWord = passWord;
            inValue.Body.hotelId = hotelId;
            HZTVApi.Business.PMSRoomStatusService.IsLoginOutRolesResponse retVal = ((HZTVApi.Business.PMSRoomStatusService.RoomStatusModifySoap)(this)).IsLoginOutRoles(inValue);
            employeeName = retVal.Body.employeeName;
            roles = retVal.Body.roles;
            hotelName = retVal.Body.hotelName;
            userPermissions = retVal.Body.userPermissions;
            return retVal.Body.IsLoginOutRolesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HZTVApi.Business.PMSRoomStatusService.IsLoginOutRolesAndEmployeeResponse HZTVApi.Business.PMSRoomStatusService.RoomStatusModifySoap.IsLoginOutRolesAndEmployee(HZTVApi.Business.PMSRoomStatusService.IsLoginOutRolesAndEmployeeRequest request) {
            return base.Channel.IsLoginOutRolesAndEmployee(request);
        }
        
        public bool IsLoginOutRolesAndEmployee(string userName, string passWord, string hotelId, out string employeeID, out string employeeName, out string roles, out string hotelName, out int userPermissions) {
            HZTVApi.Business.PMSRoomStatusService.IsLoginOutRolesAndEmployeeRequest inValue = new HZTVApi.Business.PMSRoomStatusService.IsLoginOutRolesAndEmployeeRequest();
            inValue.Body = new HZTVApi.Business.PMSRoomStatusService.IsLoginOutRolesAndEmployeeRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.passWord = passWord;
            inValue.Body.hotelId = hotelId;
            HZTVApi.Business.PMSRoomStatusService.IsLoginOutRolesAndEmployeeResponse retVal = ((HZTVApi.Business.PMSRoomStatusService.RoomStatusModifySoap)(this)).IsLoginOutRolesAndEmployee(inValue);
            employeeID = retVal.Body.employeeID;
            employeeName = retVal.Body.employeeName;
            roles = retVal.Body.roles;
            hotelName = retVal.Body.hotelName;
            userPermissions = retVal.Body.userPermissions;
            return retVal.Body.IsLoginOutRolesAndEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HZTVApi.Business.PMSRoomStatusService.IsLoginResponse HZTVApi.Business.PMSRoomStatusService.RoomStatusModifySoap.IsLogin(HZTVApi.Business.PMSRoomStatusService.IsLoginRequest request) {
            return base.Channel.IsLogin(request);
        }
        
        public bool IsLogin(string userName, string passWord, string hotelId, out string employeeName, out string hotelName, out int userPermissions) {
            HZTVApi.Business.PMSRoomStatusService.IsLoginRequest inValue = new HZTVApi.Business.PMSRoomStatusService.IsLoginRequest();
            inValue.Body = new HZTVApi.Business.PMSRoomStatusService.IsLoginRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.passWord = passWord;
            inValue.Body.hotelId = hotelId;
            HZTVApi.Business.PMSRoomStatusService.IsLoginResponse retVal = ((HZTVApi.Business.PMSRoomStatusService.RoomStatusModifySoap)(this)).IsLogin(inValue);
            employeeName = retVal.Body.employeeName;
            hotelName = retVal.Body.hotelName;
            userPermissions = retVal.Body.userPermissions;
            return retVal.Body.IsLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HZTVApi.Business.PMSRoomStatusService.IsLoginOutEmployeeResponse HZTVApi.Business.PMSRoomStatusService.RoomStatusModifySoap.IsLoginOutEmployee(HZTVApi.Business.PMSRoomStatusService.IsLoginOutEmployeeRequest request) {
            return base.Channel.IsLoginOutEmployee(request);
        }
        
        public bool IsLoginOutEmployee(string userName, string passWord, string hotelId, out string employeeID, out string employeeName, out string hotelName, out int userPermissions) {
            HZTVApi.Business.PMSRoomStatusService.IsLoginOutEmployeeRequest inValue = new HZTVApi.Business.PMSRoomStatusService.IsLoginOutEmployeeRequest();
            inValue.Body = new HZTVApi.Business.PMSRoomStatusService.IsLoginOutEmployeeRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.passWord = passWord;
            inValue.Body.hotelId = hotelId;
            HZTVApi.Business.PMSRoomStatusService.IsLoginOutEmployeeResponse retVal = ((HZTVApi.Business.PMSRoomStatusService.RoomStatusModifySoap)(this)).IsLoginOutEmployee(inValue);
            employeeID = retVal.Body.employeeID;
            employeeName = retVal.Body.employeeName;
            hotelName = retVal.Body.hotelName;
            userPermissions = retVal.Body.userPermissions;
            return retVal.Body.IsLoginOutEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HZTVApi.Business.PMSRoomStatusService.GetRoomStatusSearchByConditionResponse HZTVApi.Business.PMSRoomStatusService.RoomStatusModifySoap.GetRoomStatusSearchByCondition(HZTVApi.Business.PMSRoomStatusService.GetRoomStatusSearchByConditionRequest request) {
            return base.Channel.GetRoomStatusSearchByCondition(request);
        }
        
        public HZTVApi.Business.PMSRoomStatusService.RoomStatusInfo[] GetRoomStatusSearchByCondition(string hotelId, string roomStatusList, string roomTypeList, string roomFilter) {
            HZTVApi.Business.PMSRoomStatusService.GetRoomStatusSearchByConditionRequest inValue = new HZTVApi.Business.PMSRoomStatusService.GetRoomStatusSearchByConditionRequest();
            inValue.Body = new HZTVApi.Business.PMSRoomStatusService.GetRoomStatusSearchByConditionRequestBody();
            inValue.Body.hotelId = hotelId;
            inValue.Body.roomStatusList = roomStatusList;
            inValue.Body.roomTypeList = roomTypeList;
            inValue.Body.roomFilter = roomFilter;
            HZTVApi.Business.PMSRoomStatusService.GetRoomStatusSearchByConditionResponse retVal = ((HZTVApi.Business.PMSRoomStatusService.RoomStatusModifySoap)(this)).GetRoomStatusSearchByCondition(inValue);
            return retVal.Body.GetRoomStatusSearchByConditionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HZTVApi.Business.PMSRoomStatusService.SetCheckRoomResponse HZTVApi.Business.PMSRoomStatusService.RoomStatusModifySoap.SetCheckRoom(HZTVApi.Business.PMSRoomStatusService.SetCheckRoomRequest request) {
            return base.Channel.SetCheckRoom(request);
        }
        
        public bool SetCheckRoom(string hotelId, string roomId, string operatorId, out string msg) {
            HZTVApi.Business.PMSRoomStatusService.SetCheckRoomRequest inValue = new HZTVApi.Business.PMSRoomStatusService.SetCheckRoomRequest();
            inValue.Body = new HZTVApi.Business.PMSRoomStatusService.SetCheckRoomRequestBody();
            inValue.Body.hotelId = hotelId;
            inValue.Body.roomId = roomId;
            inValue.Body.operatorId = operatorId;
            HZTVApi.Business.PMSRoomStatusService.SetCheckRoomResponse retVal = ((HZTVApi.Business.PMSRoomStatusService.RoomStatusModifySoap)(this)).SetCheckRoom(inValue);
            msg = retVal.Body.msg;
            return retVal.Body.SetCheckRoomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HZTVApi.Business.PMSRoomStatusService.GetSystemLogsOfUnAppResponse HZTVApi.Business.PMSRoomStatusService.RoomStatusModifySoap.GetSystemLogsOfUnApp(HZTVApi.Business.PMSRoomStatusService.GetSystemLogsOfUnAppRequest request) {
            return base.Channel.GetSystemLogsOfUnApp(request);
        }
        
        public byte[] GetSystemLogsOfUnApp(string hotelId, System.DateTime startDate, System.DateTime endDate, int minutes, out string errorMsg) {
            HZTVApi.Business.PMSRoomStatusService.GetSystemLogsOfUnAppRequest inValue = new HZTVApi.Business.PMSRoomStatusService.GetSystemLogsOfUnAppRequest();
            inValue.Body = new HZTVApi.Business.PMSRoomStatusService.GetSystemLogsOfUnAppRequestBody();
            inValue.Body.hotelId = hotelId;
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            inValue.Body.minutes = minutes;
            HZTVApi.Business.PMSRoomStatusService.GetSystemLogsOfUnAppResponse retVal = ((HZTVApi.Business.PMSRoomStatusService.RoomStatusModifySoap)(this)).GetSystemLogsOfUnApp(inValue);
            errorMsg = retVal.Body.errorMsg;
            return retVal.Body.GetSystemLogsOfUnAppResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HZTVApi.Business.PMSRoomStatusService.SetCleanRoomResponse HZTVApi.Business.PMSRoomStatusService.RoomStatusModifySoap.SetCleanRoom(HZTVApi.Business.PMSRoomStatusService.SetCleanRoomRequest request) {
            return base.Channel.SetCleanRoom(request);
        }
        
        public bool SetCleanRoom(string hotelId, string roomId, string operatorId, out string msg) {
            HZTVApi.Business.PMSRoomStatusService.SetCleanRoomRequest inValue = new HZTVApi.Business.PMSRoomStatusService.SetCleanRoomRequest();
            inValue.Body = new HZTVApi.Business.PMSRoomStatusService.SetCleanRoomRequestBody();
            inValue.Body.hotelId = hotelId;
            inValue.Body.roomId = roomId;
            inValue.Body.operatorId = operatorId;
            HZTVApi.Business.PMSRoomStatusService.SetCleanRoomResponse retVal = ((HZTVApi.Business.PMSRoomStatusService.RoomStatusModifySoap)(this)).SetCleanRoom(inValue);
            msg = retVal.Body.msg;
            return retVal.Body.SetCleanRoomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HZTVApi.Business.PMSRoomStatusService.GetHotelRoomTypesResponse HZTVApi.Business.PMSRoomStatusService.RoomStatusModifySoap.GetHotelRoomTypes(HZTVApi.Business.PMSRoomStatusService.GetHotelRoomTypesRequest request) {
            return base.Channel.GetHotelRoomTypes(request);
        }
        
        public HZTVApi.Business.PMSRoomStatusService.RoomTypeEntity[] GetHotelRoomTypes(string hotelId) {
            HZTVApi.Business.PMSRoomStatusService.GetHotelRoomTypesRequest inValue = new HZTVApi.Business.PMSRoomStatusService.GetHotelRoomTypesRequest();
            inValue.Body = new HZTVApi.Business.PMSRoomStatusService.GetHotelRoomTypesRequestBody();
            inValue.Body.hotelId = hotelId;
            HZTVApi.Business.PMSRoomStatusService.GetHotelRoomTypesResponse retVal = ((HZTVApi.Business.PMSRoomStatusService.RoomStatusModifySoap)(this)).GetHotelRoomTypes(inValue);
            return retVal.Body.GetHotelRoomTypesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HZTVApi.Business.PMSRoomStatusService.GetHotelInfoResponse HZTVApi.Business.PMSRoomStatusService.RoomStatusModifySoap.GetHotelInfo(HZTVApi.Business.PMSRoomStatusService.GetHotelInfoRequest request) {
            return base.Channel.GetHotelInfo(request);
        }
        
        public HZTVApi.Business.PMSRoomStatusService.Hall[] GetHotelInfo(string hotelId) {
            HZTVApi.Business.PMSRoomStatusService.GetHotelInfoRequest inValue = new HZTVApi.Business.PMSRoomStatusService.GetHotelInfoRequest();
            inValue.Body = new HZTVApi.Business.PMSRoomStatusService.GetHotelInfoRequestBody();
            inValue.Body.hotelId = hotelId;
            HZTVApi.Business.PMSRoomStatusService.GetHotelInfoResponse retVal = ((HZTVApi.Business.PMSRoomStatusService.RoomStatusModifySoap)(this)).GetHotelInfo(inValue);
            return retVal.Body.GetHotelInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HZTVApi.Business.PMSRoomStatusService.SetOOORoomResponse HZTVApi.Business.PMSRoomStatusService.RoomStatusModifySoap.SetOOORoom(HZTVApi.Business.PMSRoomStatusService.SetOOORoomRequest request) {
            return base.Channel.SetOOORoom(request);
        }
        
        public bool SetOOORoom(string hotelId, string roomId, System.DateTime beginDate, System.DateTime endDate, string reason, string operatorId, out string msg) {
            HZTVApi.Business.PMSRoomStatusService.SetOOORoomRequest inValue = new HZTVApi.Business.PMSRoomStatusService.SetOOORoomRequest();
            inValue.Body = new HZTVApi.Business.PMSRoomStatusService.SetOOORoomRequestBody();
            inValue.Body.hotelId = hotelId;
            inValue.Body.roomId = roomId;
            inValue.Body.beginDate = beginDate;
            inValue.Body.endDate = endDate;
            inValue.Body.reason = reason;
            inValue.Body.operatorId = operatorId;
            HZTVApi.Business.PMSRoomStatusService.SetOOORoomResponse retVal = ((HZTVApi.Business.PMSRoomStatusService.RoomStatusModifySoap)(this)).SetOOORoom(inValue);
            msg = retVal.Body.msg;
            return retVal.Body.SetOOORoomResult;
        }
    }
}
