//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeahCatchHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatchHotel
    {
        public string HoteId { get; set; }
        public string HotelName { get; set; }
        public string HotelAdress { get; set; }
        public string BrandId { get; set; }
        public string BrandName { get; set; }
        public string districtId { get; set; }
        public string districtName { get; set; }
        public string HotelNameEn { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public Nullable<decimal> Lng { get; set; }
        public string Tel { get; set; }
        public string Image { get; set; }
        public string TokenUrl { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string InnId { get; set; }
    }
}
