//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeahCatchHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatHotelLog
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public string Status { get; set; }
        public string Token { get; set; }
        public string HotelType { get; set; }
    }
}
