//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HZTVApi.Business.PMS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RcpnSheetDataContract", Namespace="http://schemas.datacontract.org/2004/07/HuaZhu.PMS.Interface.SmartTVService.DataC" +
        "ontract")]
    [System.SerializableAttribute()]
    public partial class RcpnSheetDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CheckInDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CheckOutDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CheckinSrcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CusCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CusNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CusTelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InmateRecIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemberIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecStatusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNo {
            get {
                return this.CardNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNoField, value) != true)) {
                    this.CardNoField = value;
                    this.RaisePropertyChanged("CardNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CheckInDate {
            get {
                return this.CheckInDateField;
            }
            set {
                if ((this.CheckInDateField.Equals(value) != true)) {
                    this.CheckInDateField = value;
                    this.RaisePropertyChanged("CheckInDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CheckOutDate {
            get {
                return this.CheckOutDateField;
            }
            set {
                if ((this.CheckOutDateField.Equals(value) != true)) {
                    this.CheckOutDateField = value;
                    this.RaisePropertyChanged("CheckOutDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheckinSrc {
            get {
                return this.CheckinSrcField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckinSrcField, value) != true)) {
                    this.CheckinSrcField = value;
                    this.RaisePropertyChanged("CheckinSrc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CusCategory {
            get {
                return this.CusCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CusCategoryField, value) != true)) {
                    this.CusCategoryField = value;
                    this.RaisePropertyChanged("CusCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CusName {
            get {
                return this.CusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CusNameField, value) != true)) {
                    this.CusNameField = value;
                    this.RaisePropertyChanged("CusName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CusTel {
            get {
                return this.CusTelField;
            }
            set {
                if ((object.ReferenceEquals(this.CusTelField, value) != true)) {
                    this.CusTelField = value;
                    this.RaisePropertyChanged("CusTel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDType {
            get {
                return this.IDTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.IDTypeField, value) != true)) {
                    this.IDTypeField = value;
                    this.RaisePropertyChanged("IDType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InmateRecID {
            get {
                return this.InmateRecIDField;
            }
            set {
                if ((object.ReferenceEquals(this.InmateRecIDField, value) != true)) {
                    this.InmateRecIDField = value;
                    this.RaisePropertyChanged("InmateRecID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MemberID {
            get {
                return this.MemberIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberIDField, value) != true)) {
                    this.MemberIDField = value;
                    this.RaisePropertyChanged("MemberID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecStatusID {
            get {
                return this.RecStatusIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RecStatusIDField, value) != true)) {
                    this.RecStatusIDField = value;
                    this.RaisePropertyChanged("RecStatusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiveID {
            get {
                return this.ReceiveIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveIDField, value) != true)) {
                    this.ReceiveIDField = value;
                    this.RaisePropertyChanged("ReceiveID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MorningCallDataContract", Namespace="http://schemas.datacontract.org/2004/07/HuaZhu.PMS.Interface.SmartTVService.DataC" +
        "ontract")]
    [System.SerializableAttribute()]
    public partial class MorningCallDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CallTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CusAccIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CusNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InterludeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string McIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ModifyDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperatorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CallTime {
            get {
                return this.CallTimeField;
            }
            set {
                if ((this.CallTimeField.Equals(value) != true)) {
                    this.CallTimeField = value;
                    this.RaisePropertyChanged("CallTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cnt {
            get {
                return this.CntField;
            }
            set {
                if ((this.CntField.Equals(value) != true)) {
                    this.CntField = value;
                    this.RaisePropertyChanged("Cnt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CusAccID {
            get {
                return this.CusAccIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CusAccIDField, value) != true)) {
                    this.CusAccIDField = value;
                    this.RaisePropertyChanged("CusAccID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CusName {
            get {
                return this.CusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CusNameField, value) != true)) {
                    this.CusNameField = value;
                    this.RaisePropertyChanged("CusName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelID {
            get {
                return this.HotelIDField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelIDField, value) != true)) {
                    this.HotelIDField = value;
                    this.RaisePropertyChanged("HotelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Interlude {
            get {
                return this.InterludeField;
            }
            set {
                if ((this.InterludeField.Equals(value) != true)) {
                    this.InterludeField = value;
                    this.RaisePropertyChanged("Interlude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string McID {
            get {
                return this.McIDField;
            }
            set {
                if ((object.ReferenceEquals(this.McIDField, value) != true)) {
                    this.McIDField = value;
                    this.RaisePropertyChanged("McID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Memo {
            get {
                return this.MemoField;
            }
            set {
                if ((object.ReferenceEquals(this.MemoField, value) != true)) {
                    this.MemoField = value;
                    this.RaisePropertyChanged("Memo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifyDate {
            get {
                return this.ModifyDateField;
            }
            set {
                if ((this.ModifyDateField.Equals(value) != true)) {
                    this.ModifyDateField = value;
                    this.RaisePropertyChanged("ModifyDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperatorID {
            get {
                return this.OperatorIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatorIDField, value) != true)) {
                    this.OperatorIDField = value;
                    this.RaisePropertyChanged("OperatorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiveID {
            get {
                return this.ReceiveIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveIDField, value) != true)) {
                    this.ReceiveIDField = value;
                    this.RaisePropertyChanged("ReceiveID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusID {
            get {
                return this.StatusIDField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusIDField, value) != true)) {
                    this.StatusIDField = value;
                    this.RaisePropertyChanged("StatusID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseResultDataContract", Namespace="http://schemas.datacontract.org/2004/07/HuaZhu.PMS.Interface.SmartTVService.DataC" +
        "ontract")]
    [System.SerializableAttribute()]
    public partial class ResponseResultDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrogMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrogMsg {
            get {
                return this.ErrogMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrogMsgField, value) != true)) {
                    this.ErrogMsgField = value;
                    this.RaisePropertyChanged("ErrogMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PMS.IPmsService")]
    public interface IPmsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPmsService/GetRcpnSheetInfoByRoomNo", ReplyAction="http://tempuri.org/IPmsService/GetRcpnSheetInfoByRoomNoResponse")]
        HZTVApi.Business.PMS.RcpnSheetDataContract[] GetRcpnSheetInfoByRoomNo(string hotelID, string roomNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPmsService/GetMorningCallByRoomNo", ReplyAction="http://tempuri.org/IPmsService/GetMorningCallByRoomNoResponse")]
        HZTVApi.Business.PMS.MorningCallDataContract[] GetMorningCallByRoomNo(string hotelID, string roomNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPmsService/SetMorningCall", ReplyAction="http://tempuri.org/IPmsService/SetMorningCallResponse")]
        HZTVApi.Business.PMS.ResponseResultDataContract SetMorningCall(string hotelID, string roomNo, System.DateTime callTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPmsService/CancelMorningCall", ReplyAction="http://tempuri.org/IPmsService/CancelMorningCallResponse")]
        int CancelMorningCall(string hotelID, string roomNo, string[] mcIDs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPmsServiceChannel : HZTVApi.Business.PMS.IPmsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PmsServiceClient : System.ServiceModel.ClientBase<HZTVApi.Business.PMS.IPmsService>, HZTVApi.Business.PMS.IPmsService {
        
        public PmsServiceClient() {
        }
        
        public PmsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PmsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PmsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PmsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HZTVApi.Business.PMS.RcpnSheetDataContract[] GetRcpnSheetInfoByRoomNo(string hotelID, string roomNo) {
            return base.Channel.GetRcpnSheetInfoByRoomNo(hotelID, roomNo);
        }
        
        public HZTVApi.Business.PMS.MorningCallDataContract[] GetMorningCallByRoomNo(string hotelID, string roomNo) {
            return base.Channel.GetMorningCallByRoomNo(hotelID, roomNo);
        }
        
        public HZTVApi.Business.PMS.ResponseResultDataContract SetMorningCall(string hotelID, string roomNo, System.DateTime callTime) {
            return base.Channel.SetMorningCall(hotelID, roomNo, callTime);
        }
        
        public int CancelMorningCall(string hotelID, string roomNo, string[] mcIDs) {
            return base.Channel.CancelMorningCall(hotelID, roomNo, mcIDs);
        }
    }
}
