//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeahTVApi.ServiceProvider.PMSRoomStatusService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomStatusInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RoomStatusInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private YeahTVApi.ServiceProvider.PMSRoomStatusService.ArrayOfString AttributeField;
        
        private System.DateTime PlanLeaveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HallIdField;
        
        private System.DateTime ModifyTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.ArrayOfString Attribute {
            get {
                return this.AttributeField;
            }
            set {
                if ((object.ReferenceEquals(this.AttributeField, value) != true)) {
                    this.AttributeField = value;
                    this.RaisePropertyChanged("Attribute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime PlanLeaveDate {
            get {
                return this.PlanLeaveDateField;
            }
            set {
                if ((this.PlanLeaveDateField.Equals(value) != true)) {
                    this.PlanLeaveDateField = value;
                    this.RaisePropertyChanged("PlanLeaveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RoomNumber {
            get {
                return this.RoomNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomNumberField, value) != true)) {
                    this.RoomNumberField = value;
                    this.RaisePropertyChanged("RoomNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string RoomTypeID {
            get {
                return this.RoomTypeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomTypeIDField, value) != true)) {
                    this.RoomTypeIDField = value;
                    this.RaisePropertyChanged("RoomTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string RoomTypeName {
            get {
                return this.RoomTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomTypeNameField, value) != true)) {
                    this.RoomTypeNameField = value;
                    this.RaisePropertyChanged("RoomTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string HallId {
            get {
                return this.HallIdField;
            }
            set {
                if ((object.ReferenceEquals(this.HallIdField, value) != true)) {
                    this.HallIdField = value;
                    this.RaisePropertyChanged("HallId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime ModifyTime {
            get {
                return this.ModifyTimeField;
            }
            set {
                if ((this.ModifyTimeField.Equals(value) != true)) {
                    this.ModifyTimeField = value;
                    this.RaisePropertyChanged("ModifyTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomTypeEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RoomTypeEntity : YeahTVApi.ServiceProvider.PMSRoomStatusService.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomTypeIDField;
        
        private int BedNumField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RoomTypeName {
            get {
                return this.RoomTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomTypeNameField, value) != true)) {
                    this.RoomTypeNameField = value;
                    this.RaisePropertyChanged("RoomTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RoomTypeID {
            get {
                return this.RoomTypeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomTypeIDField, value) != true)) {
                    this.RoomTypeIDField = value;
                    this.RaisePropertyChanged("RoomTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int BedNum {
            get {
                return this.BedNumField;
            }
            set {
                if ((this.BedNumField.Equals(value) != true)) {
                    this.BedNumField = value;
                    this.RaisePropertyChanged("BedNum");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityBase", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomTypeEntity))]
    public partial class EntityBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hall", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Hall : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HallIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HallNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private YeahTVApi.ServiceProvider.PMSRoomStatusService.Floor[] FloorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string HallID {
            get {
                return this.HallIDField;
            }
            set {
                if ((object.ReferenceEquals(this.HallIDField, value) != true)) {
                    this.HallIDField = value;
                    this.RaisePropertyChanged("HallID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string HallName {
            get {
                return this.HallNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HallNameField, value) != true)) {
                    this.HallNameField = value;
                    this.RaisePropertyChanged("HallName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.Floor[] Floors {
            get {
                return this.FloorsField;
            }
            set {
                if ((object.ReferenceEquals(this.FloorsField, value) != true)) {
                    this.FloorsField = value;
                    this.RaisePropertyChanged("Floors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Floor", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Floor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FloorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FloorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private YeahTVApi.ServiceProvider.PMSRoomStatusService.Chamber[] RoomsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoordinateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FloorID {
            get {
                return this.FloorIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FloorIDField, value) != true)) {
                    this.FloorIDField = value;
                    this.RaisePropertyChanged("FloorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FloorName {
            get {
                return this.FloorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FloorNameField, value) != true)) {
                    this.FloorNameField = value;
                    this.RaisePropertyChanged("FloorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.Chamber[] Rooms {
            get {
                return this.RoomsField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomsField, value) != true)) {
                    this.RoomsField = value;
                    this.RaisePropertyChanged("Rooms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Coordinate {
            get {
                return this.CoordinateField;
            }
            set {
                if ((object.ReferenceEquals(this.CoordinateField, value) != true)) {
                    this.CoordinateField = value;
                    this.RaisePropertyChanged("Coordinate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Chamber", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Chamber : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChamberNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChamberTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StoreyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoordinateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomTrait[] HobbyCollectionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ChamberNumber {
            get {
                return this.ChamberNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ChamberNumberField, value) != true)) {
                    this.ChamberNumberField = value;
                    this.RaisePropertyChanged("ChamberNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ChamberType {
            get {
                return this.ChamberTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ChamberTypeField, value) != true)) {
                    this.ChamberTypeField = value;
                    this.RaisePropertyChanged("ChamberType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Storey {
            get {
                return this.StoreyField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreyField, value) != true)) {
                    this.StoreyField = value;
                    this.RaisePropertyChanged("Storey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Building {
            get {
                return this.BuildingField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingField, value) != true)) {
                    this.BuildingField = value;
                    this.RaisePropertyChanged("Building");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Coordinate {
            get {
                return this.CoordinateField;
            }
            set {
                if ((object.ReferenceEquals(this.CoordinateField, value) != true)) {
                    this.CoordinateField = value;
                    this.RaisePropertyChanged("Coordinate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomTrait[] HobbyCollection {
            get {
                return this.HobbyCollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.HobbyCollectionField, value) != true)) {
                    this.HobbyCollectionField = value;
                    this.RaisePropertyChanged("HobbyCollection");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomTrait", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RoomTrait : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TraitKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TraitTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TraitKey {
            get {
                return this.TraitKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.TraitKeyField, value) != true)) {
                    this.TraitKeyField = value;
                    this.RaisePropertyChanged("TraitKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TraitText {
            get {
                return this.TraitTextField;
            }
            set {
                if ((object.ReferenceEquals(this.TraitTextField, value) != true)) {
                    this.TraitTextField = value;
                    this.RaisePropertyChanged("TraitText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PMSRoomStatusService.RoomStatusModifySoap")]
    public interface RoomStatusModifySoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsLoginOutRoles", ReplyAction="*")]
        YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginOutRolesResponse IsLoginOutRoles(YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginOutRolesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsLoginOutRoles", ReplyAction="*")]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginOutRolesResponse> IsLoginOutRolesAsync(YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginOutRolesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsLogin", ReplyAction="*")]
        YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginResponse IsLogin(YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginResponse> IsLoginAsync(YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginRequest request);
        
        // CODEGEN: Generating message contract since element name hotelId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRoomStatusSearchByCondition", ReplyAction="*")]
        YeahTVApi.ServiceProvider.PMSRoomStatusService.GetRoomStatusSearchByConditionResponse GetRoomStatusSearchByCondition(YeahTVApi.ServiceProvider.PMSRoomStatusService.GetRoomStatusSearchByConditionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRoomStatusSearchByCondition", ReplyAction="*")]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMSRoomStatusService.GetRoomStatusSearchByConditionResponse> GetRoomStatusSearchByConditionAsync(YeahTVApi.ServiceProvider.PMSRoomStatusService.GetRoomStatusSearchByConditionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetCheckRoom", ReplyAction="*")]
        YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCheckRoomResponse SetCheckRoom(YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCheckRoomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetCheckRoom", ReplyAction="*")]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCheckRoomResponse> SetCheckRoomAsync(YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCheckRoomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSystemLogsOfUnApp", ReplyAction="*")]
        YeahTVApi.ServiceProvider.PMSRoomStatusService.GetSystemLogsOfUnAppResponse GetSystemLogsOfUnApp(YeahTVApi.ServiceProvider.PMSRoomStatusService.GetSystemLogsOfUnAppRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSystemLogsOfUnApp", ReplyAction="*")]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMSRoomStatusService.GetSystemLogsOfUnAppResponse> GetSystemLogsOfUnAppAsync(YeahTVApi.ServiceProvider.PMSRoomStatusService.GetSystemLogsOfUnAppRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetCleanRoom", ReplyAction="*")]
        YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCleanRoomResponse SetCleanRoom(YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCleanRoomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetCleanRoom", ReplyAction="*")]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCleanRoomResponse> SetCleanRoomAsync(YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCleanRoomRequest request);
        
        // CODEGEN: Generating message contract since element name hotelId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHotelRoomTypes", ReplyAction="*")]
        YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelRoomTypesResponse GetHotelRoomTypes(YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelRoomTypesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHotelRoomTypes", ReplyAction="*")]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelRoomTypesResponse> GetHotelRoomTypesAsync(YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelRoomTypesRequest request);
        
        // CODEGEN: Generating message contract since element name hotelId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHotelInfo", ReplyAction="*")]
        YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelInfoResponse GetHotelInfo(YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHotelInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelInfoResponse> GetHotelInfoAsync(YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetOOORoom", ReplyAction="*")]
        YeahTVApi.ServiceProvider.PMSRoomStatusService.SetOOORoomResponse SetOOORoom(YeahTVApi.ServiceProvider.PMSRoomStatusService.SetOOORoomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetOOORoom", ReplyAction="*")]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMSRoomStatusService.SetOOORoomResponse> SetOOORoomAsync(YeahTVApi.ServiceProvider.PMSRoomStatusService.SetOOORoomRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsLoginOutRolesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsLoginOutRoles", Namespace="http://tempuri.org/", Order=0)]
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginOutRolesRequestBody Body;
        
        public IsLoginOutRolesRequest() {
        }
        
        public IsLoginOutRolesRequest(YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginOutRolesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsLoginOutRolesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passWord;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string hotelId;
        
        public IsLoginOutRolesRequestBody() {
        }
        
        public IsLoginOutRolesRequestBody(string userName, string passWord, string hotelId) {
            this.userName = userName;
            this.passWord = passWord;
            this.hotelId = hotelId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsLoginOutRolesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsLoginOutRolesResponse", Namespace="http://tempuri.org/", Order=0)]
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginOutRolesResponseBody Body;
        
        public IsLoginOutRolesResponse() {
        }
        
        public IsLoginOutRolesResponse(YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginOutRolesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsLoginOutRolesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsLoginOutRolesResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string employeeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string roles;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string hotelName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int userPermissions;
        
        public IsLoginOutRolesResponseBody() {
        }
        
        public IsLoginOutRolesResponseBody(bool IsLoginOutRolesResult, string employeeName, string roles, string hotelName, int userPermissions) {
            this.IsLoginOutRolesResult = IsLoginOutRolesResult;
            this.employeeName = employeeName;
            this.roles = roles;
            this.hotelName = hotelName;
            this.userPermissions = userPermissions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsLogin", Namespace="http://tempuri.org/", Order=0)]
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginRequestBody Body;
        
        public IsLoginRequest() {
        }
        
        public IsLoginRequest(YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passWord;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string hotelId;
        
        public IsLoginRequestBody() {
        }
        
        public IsLoginRequestBody(string userName, string passWord, string hotelId) {
            this.userName = userName;
            this.passWord = passWord;
            this.hotelId = hotelId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginResponseBody Body;
        
        public IsLoginResponse() {
        }
        
        public IsLoginResponse(YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsLoginResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string employeeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string hotelName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int userPermissions;
        
        public IsLoginResponseBody() {
        }
        
        public IsLoginResponseBody(bool IsLoginResult, string employeeName, string hotelName, int userPermissions) {
            this.IsLoginResult = IsLoginResult;
            this.employeeName = employeeName;
            this.hotelName = hotelName;
            this.userPermissions = userPermissions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRoomStatusSearchByConditionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRoomStatusSearchByCondition", Namespace="http://tempuri.org/", Order=0)]
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.GetRoomStatusSearchByConditionRequestBody Body;
        
        public GetRoomStatusSearchByConditionRequest() {
        }
        
        public GetRoomStatusSearchByConditionRequest(YeahTVApi.ServiceProvider.PMSRoomStatusService.GetRoomStatusSearchByConditionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRoomStatusSearchByConditionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hotelId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string roomStatusList;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string roomTypeList;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string roomFilter;
        
        public GetRoomStatusSearchByConditionRequestBody() {
        }
        
        public GetRoomStatusSearchByConditionRequestBody(string hotelId, string roomStatusList, string roomTypeList, string roomFilter) {
            this.hotelId = hotelId;
            this.roomStatusList = roomStatusList;
            this.roomTypeList = roomTypeList;
            this.roomFilter = roomFilter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRoomStatusSearchByConditionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRoomStatusSearchByConditionResponse", Namespace="http://tempuri.org/", Order=0)]
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.GetRoomStatusSearchByConditionResponseBody Body;
        
        public GetRoomStatusSearchByConditionResponse() {
        }
        
        public GetRoomStatusSearchByConditionResponse(YeahTVApi.ServiceProvider.PMSRoomStatusService.GetRoomStatusSearchByConditionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRoomStatusSearchByConditionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusInfo[] GetRoomStatusSearchByConditionResult;
        
        public GetRoomStatusSearchByConditionResponseBody() {
        }
        
        public GetRoomStatusSearchByConditionResponseBody(YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusInfo[] GetRoomStatusSearchByConditionResult) {
            this.GetRoomStatusSearchByConditionResult = GetRoomStatusSearchByConditionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCheckRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetCheckRoom", Namespace="http://tempuri.org/", Order=0)]
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCheckRoomRequestBody Body;
        
        public SetCheckRoomRequest() {
        }
        
        public SetCheckRoomRequest(YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCheckRoomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetCheckRoomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hotelId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string roomId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string operatorId;
        
        public SetCheckRoomRequestBody() {
        }
        
        public SetCheckRoomRequestBody(string hotelId, string roomId, string operatorId) {
            this.hotelId = hotelId;
            this.roomId = roomId;
            this.operatorId = operatorId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCheckRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetCheckRoomResponse", Namespace="http://tempuri.org/", Order=0)]
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCheckRoomResponseBody Body;
        
        public SetCheckRoomResponse() {
        }
        
        public SetCheckRoomResponse(YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCheckRoomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetCheckRoomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetCheckRoomResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg;
        
        public SetCheckRoomResponseBody() {
        }
        
        public SetCheckRoomResponseBody(bool SetCheckRoomResult, string msg) {
            this.SetCheckRoomResult = SetCheckRoomResult;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSystemLogsOfUnAppRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSystemLogsOfUnApp", Namespace="http://tempuri.org/", Order=0)]
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.GetSystemLogsOfUnAppRequestBody Body;
        
        public GetSystemLogsOfUnAppRequest() {
        }
        
        public GetSystemLogsOfUnAppRequest(YeahTVApi.ServiceProvider.PMSRoomStatusService.GetSystemLogsOfUnAppRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSystemLogsOfUnAppRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hotelId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime startDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime endDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int minutes;
        
        public GetSystemLogsOfUnAppRequestBody() {
        }
        
        public GetSystemLogsOfUnAppRequestBody(string hotelId, System.DateTime startDate, System.DateTime endDate, int minutes) {
            this.hotelId = hotelId;
            this.startDate = startDate;
            this.endDate = endDate;
            this.minutes = minutes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSystemLogsOfUnAppResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSystemLogsOfUnAppResponse", Namespace="http://tempuri.org/", Order=0)]
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.GetSystemLogsOfUnAppResponseBody Body;
        
        public GetSystemLogsOfUnAppResponse() {
        }
        
        public GetSystemLogsOfUnAppResponse(YeahTVApi.ServiceProvider.PMSRoomStatusService.GetSystemLogsOfUnAppResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSystemLogsOfUnAppResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetSystemLogsOfUnAppResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errorMsg;
        
        public GetSystemLogsOfUnAppResponseBody() {
        }
        
        public GetSystemLogsOfUnAppResponseBody(byte[] GetSystemLogsOfUnAppResult, string errorMsg) {
            this.GetSystemLogsOfUnAppResult = GetSystemLogsOfUnAppResult;
            this.errorMsg = errorMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCleanRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetCleanRoom", Namespace="http://tempuri.org/", Order=0)]
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCleanRoomRequestBody Body;
        
        public SetCleanRoomRequest() {
        }
        
        public SetCleanRoomRequest(YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCleanRoomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetCleanRoomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hotelId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string roomId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string operatorId;
        
        public SetCleanRoomRequestBody() {
        }
        
        public SetCleanRoomRequestBody(string hotelId, string roomId, string operatorId) {
            this.hotelId = hotelId;
            this.roomId = roomId;
            this.operatorId = operatorId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCleanRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetCleanRoomResponse", Namespace="http://tempuri.org/", Order=0)]
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCleanRoomResponseBody Body;
        
        public SetCleanRoomResponse() {
        }
        
        public SetCleanRoomResponse(YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCleanRoomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetCleanRoomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetCleanRoomResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg;
        
        public SetCleanRoomResponseBody() {
        }
        
        public SetCleanRoomResponseBody(bool SetCleanRoomResult, string msg) {
            this.SetCleanRoomResult = SetCleanRoomResult;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHotelRoomTypesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHotelRoomTypes", Namespace="http://tempuri.org/", Order=0)]
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelRoomTypesRequestBody Body;
        
        public GetHotelRoomTypesRequest() {
        }
        
        public GetHotelRoomTypesRequest(YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelRoomTypesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHotelRoomTypesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hotelId;
        
        public GetHotelRoomTypesRequestBody() {
        }
        
        public GetHotelRoomTypesRequestBody(string hotelId) {
            this.hotelId = hotelId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHotelRoomTypesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHotelRoomTypesResponse", Namespace="http://tempuri.org/", Order=0)]
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelRoomTypesResponseBody Body;
        
        public GetHotelRoomTypesResponse() {
        }
        
        public GetHotelRoomTypesResponse(YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelRoomTypesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHotelRoomTypesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomTypeEntity[] GetHotelRoomTypesResult;
        
        public GetHotelRoomTypesResponseBody() {
        }
        
        public GetHotelRoomTypesResponseBody(YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomTypeEntity[] GetHotelRoomTypesResult) {
            this.GetHotelRoomTypesResult = GetHotelRoomTypesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHotelInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHotelInfo", Namespace="http://tempuri.org/", Order=0)]
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelInfoRequestBody Body;
        
        public GetHotelInfoRequest() {
        }
        
        public GetHotelInfoRequest(YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHotelInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hotelId;
        
        public GetHotelInfoRequestBody() {
        }
        
        public GetHotelInfoRequestBody(string hotelId) {
            this.hotelId = hotelId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHotelInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHotelInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelInfoResponseBody Body;
        
        public GetHotelInfoResponse() {
        }
        
        public GetHotelInfoResponse(YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHotelInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.Hall[] GetHotelInfoResult;
        
        public GetHotelInfoResponseBody() {
        }
        
        public GetHotelInfoResponseBody(YeahTVApi.ServiceProvider.PMSRoomStatusService.Hall[] GetHotelInfoResult) {
            this.GetHotelInfoResult = GetHotelInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetOOORoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetOOORoom", Namespace="http://tempuri.org/", Order=0)]
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.SetOOORoomRequestBody Body;
        
        public SetOOORoomRequest() {
        }
        
        public SetOOORoomRequest(YeahTVApi.ServiceProvider.PMSRoomStatusService.SetOOORoomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetOOORoomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hotelId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string roomId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime beginDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime endDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string reason;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string operatorId;
        
        public SetOOORoomRequestBody() {
        }
        
        public SetOOORoomRequestBody(string hotelId, string roomId, System.DateTime beginDate, System.DateTime endDate, string reason, string operatorId) {
            this.hotelId = hotelId;
            this.roomId = roomId;
            this.beginDate = beginDate;
            this.endDate = endDate;
            this.reason = reason;
            this.operatorId = operatorId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetOOORoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetOOORoomResponse", Namespace="http://tempuri.org/", Order=0)]
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.SetOOORoomResponseBody Body;
        
        public SetOOORoomResponse() {
        }
        
        public SetOOORoomResponse(YeahTVApi.ServiceProvider.PMSRoomStatusService.SetOOORoomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetOOORoomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetOOORoomResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg;
        
        public SetOOORoomResponseBody() {
        }
        
        public SetOOORoomResponseBody(bool SetOOORoomResult, string msg) {
            this.SetOOORoomResult = SetOOORoomResult;
            this.msg = msg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RoomStatusModifySoapChannel : YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoomStatusModifySoapClient : System.ServiceModel.ClientBase<YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap>, YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap {
        
        public RoomStatusModifySoapClient() {
        }
        
        public RoomStatusModifySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoomStatusModifySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomStatusModifySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomStatusModifySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginOutRolesResponse YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap.IsLoginOutRoles(YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginOutRolesRequest request) {
            return base.Channel.IsLoginOutRoles(request);
        }
        
        public bool IsLoginOutRoles(string userName, string passWord, string hotelId, out string employeeName, out string roles, out string hotelName, out int userPermissions) {
            YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginOutRolesRequest inValue = new YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginOutRolesRequest();
            inValue.Body = new YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginOutRolesRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.passWord = passWord;
            inValue.Body.hotelId = hotelId;
            YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginOutRolesResponse retVal = ((YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap)(this)).IsLoginOutRoles(inValue);
            employeeName = retVal.Body.employeeName;
            roles = retVal.Body.roles;
            hotelName = retVal.Body.hotelName;
            userPermissions = retVal.Body.userPermissions;
            return retVal.Body.IsLoginOutRolesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginOutRolesResponse> YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap.IsLoginOutRolesAsync(YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginOutRolesRequest request) {
            return base.Channel.IsLoginOutRolesAsync(request);
        }
        
        public System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginOutRolesResponse> IsLoginOutRolesAsync(string userName, string passWord, string hotelId) {
            YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginOutRolesRequest inValue = new YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginOutRolesRequest();
            inValue.Body = new YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginOutRolesRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.passWord = passWord;
            inValue.Body.hotelId = hotelId;
            return ((YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap)(this)).IsLoginOutRolesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginResponse YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap.IsLogin(YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginRequest request) {
            return base.Channel.IsLogin(request);
        }
        
        public bool IsLogin(string userName, string passWord, string hotelId, out string employeeName, out string hotelName, out int userPermissions) {
            YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginRequest inValue = new YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginRequest();
            inValue.Body = new YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.passWord = passWord;
            inValue.Body.hotelId = hotelId;
            YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginResponse retVal = ((YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap)(this)).IsLogin(inValue);
            employeeName = retVal.Body.employeeName;
            hotelName = retVal.Body.hotelName;
            userPermissions = retVal.Body.userPermissions;
            return retVal.Body.IsLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginResponse> YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap.IsLoginAsync(YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginRequest request) {
            return base.Channel.IsLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginResponse> IsLoginAsync(string userName, string passWord, string hotelId) {
            YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginRequest inValue = new YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginRequest();
            inValue.Body = new YeahTVApi.ServiceProvider.PMSRoomStatusService.IsLoginRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.passWord = passWord;
            inValue.Body.hotelId = hotelId;
            return ((YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap)(this)).IsLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YeahTVApi.ServiceProvider.PMSRoomStatusService.GetRoomStatusSearchByConditionResponse YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap.GetRoomStatusSearchByCondition(YeahTVApi.ServiceProvider.PMSRoomStatusService.GetRoomStatusSearchByConditionRequest request) {
            return base.Channel.GetRoomStatusSearchByCondition(request);
        }
        
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusInfo[] GetRoomStatusSearchByCondition(string hotelId, string roomStatusList, string roomTypeList, string roomFilter) {
            YeahTVApi.ServiceProvider.PMSRoomStatusService.GetRoomStatusSearchByConditionRequest inValue = new YeahTVApi.ServiceProvider.PMSRoomStatusService.GetRoomStatusSearchByConditionRequest();
            inValue.Body = new YeahTVApi.ServiceProvider.PMSRoomStatusService.GetRoomStatusSearchByConditionRequestBody();
            inValue.Body.hotelId = hotelId;
            inValue.Body.roomStatusList = roomStatusList;
            inValue.Body.roomTypeList = roomTypeList;
            inValue.Body.roomFilter = roomFilter;
            YeahTVApi.ServiceProvider.PMSRoomStatusService.GetRoomStatusSearchByConditionResponse retVal = ((YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap)(this)).GetRoomStatusSearchByCondition(inValue);
            return retVal.Body.GetRoomStatusSearchByConditionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMSRoomStatusService.GetRoomStatusSearchByConditionResponse> YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap.GetRoomStatusSearchByConditionAsync(YeahTVApi.ServiceProvider.PMSRoomStatusService.GetRoomStatusSearchByConditionRequest request) {
            return base.Channel.GetRoomStatusSearchByConditionAsync(request);
        }
        
        public System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMSRoomStatusService.GetRoomStatusSearchByConditionResponse> GetRoomStatusSearchByConditionAsync(string hotelId, string roomStatusList, string roomTypeList, string roomFilter) {
            YeahTVApi.ServiceProvider.PMSRoomStatusService.GetRoomStatusSearchByConditionRequest inValue = new YeahTVApi.ServiceProvider.PMSRoomStatusService.GetRoomStatusSearchByConditionRequest();
            inValue.Body = new YeahTVApi.ServiceProvider.PMSRoomStatusService.GetRoomStatusSearchByConditionRequestBody();
            inValue.Body.hotelId = hotelId;
            inValue.Body.roomStatusList = roomStatusList;
            inValue.Body.roomTypeList = roomTypeList;
            inValue.Body.roomFilter = roomFilter;
            return ((YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap)(this)).GetRoomStatusSearchByConditionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCheckRoomResponse YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap.SetCheckRoom(YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCheckRoomRequest request) {
            return base.Channel.SetCheckRoom(request);
        }
        
        public bool SetCheckRoom(string hotelId, string roomId, string operatorId, out string msg) {
            YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCheckRoomRequest inValue = new YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCheckRoomRequest();
            inValue.Body = new YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCheckRoomRequestBody();
            inValue.Body.hotelId = hotelId;
            inValue.Body.roomId = roomId;
            inValue.Body.operatorId = operatorId;
            YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCheckRoomResponse retVal = ((YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap)(this)).SetCheckRoom(inValue);
            msg = retVal.Body.msg;
            return retVal.Body.SetCheckRoomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCheckRoomResponse> YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap.SetCheckRoomAsync(YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCheckRoomRequest request) {
            return base.Channel.SetCheckRoomAsync(request);
        }
        
        public System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCheckRoomResponse> SetCheckRoomAsync(string hotelId, string roomId, string operatorId) {
            YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCheckRoomRequest inValue = new YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCheckRoomRequest();
            inValue.Body = new YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCheckRoomRequestBody();
            inValue.Body.hotelId = hotelId;
            inValue.Body.roomId = roomId;
            inValue.Body.operatorId = operatorId;
            return ((YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap)(this)).SetCheckRoomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YeahTVApi.ServiceProvider.PMSRoomStatusService.GetSystemLogsOfUnAppResponse YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap.GetSystemLogsOfUnApp(YeahTVApi.ServiceProvider.PMSRoomStatusService.GetSystemLogsOfUnAppRequest request) {
            return base.Channel.GetSystemLogsOfUnApp(request);
        }
        
        public byte[] GetSystemLogsOfUnApp(string hotelId, System.DateTime startDate, System.DateTime endDate, int minutes, out string errorMsg) {
            YeahTVApi.ServiceProvider.PMSRoomStatusService.GetSystemLogsOfUnAppRequest inValue = new YeahTVApi.ServiceProvider.PMSRoomStatusService.GetSystemLogsOfUnAppRequest();
            inValue.Body = new YeahTVApi.ServiceProvider.PMSRoomStatusService.GetSystemLogsOfUnAppRequestBody();
            inValue.Body.hotelId = hotelId;
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            inValue.Body.minutes = minutes;
            YeahTVApi.ServiceProvider.PMSRoomStatusService.GetSystemLogsOfUnAppResponse retVal = ((YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap)(this)).GetSystemLogsOfUnApp(inValue);
            errorMsg = retVal.Body.errorMsg;
            return retVal.Body.GetSystemLogsOfUnAppResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMSRoomStatusService.GetSystemLogsOfUnAppResponse> YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap.GetSystemLogsOfUnAppAsync(YeahTVApi.ServiceProvider.PMSRoomStatusService.GetSystemLogsOfUnAppRequest request) {
            return base.Channel.GetSystemLogsOfUnAppAsync(request);
        }
        
        public System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMSRoomStatusService.GetSystemLogsOfUnAppResponse> GetSystemLogsOfUnAppAsync(string hotelId, System.DateTime startDate, System.DateTime endDate, int minutes) {
            YeahTVApi.ServiceProvider.PMSRoomStatusService.GetSystemLogsOfUnAppRequest inValue = new YeahTVApi.ServiceProvider.PMSRoomStatusService.GetSystemLogsOfUnAppRequest();
            inValue.Body = new YeahTVApi.ServiceProvider.PMSRoomStatusService.GetSystemLogsOfUnAppRequestBody();
            inValue.Body.hotelId = hotelId;
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            inValue.Body.minutes = minutes;
            return ((YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap)(this)).GetSystemLogsOfUnAppAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCleanRoomResponse YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap.SetCleanRoom(YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCleanRoomRequest request) {
            return base.Channel.SetCleanRoom(request);
        }
        
        public bool SetCleanRoom(string hotelId, string roomId, string operatorId, out string msg) {
            YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCleanRoomRequest inValue = new YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCleanRoomRequest();
            inValue.Body = new YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCleanRoomRequestBody();
            inValue.Body.hotelId = hotelId;
            inValue.Body.roomId = roomId;
            inValue.Body.operatorId = operatorId;
            YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCleanRoomResponse retVal = ((YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap)(this)).SetCleanRoom(inValue);
            msg = retVal.Body.msg;
            return retVal.Body.SetCleanRoomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCleanRoomResponse> YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap.SetCleanRoomAsync(YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCleanRoomRequest request) {
            return base.Channel.SetCleanRoomAsync(request);
        }
        
        public System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCleanRoomResponse> SetCleanRoomAsync(string hotelId, string roomId, string operatorId) {
            YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCleanRoomRequest inValue = new YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCleanRoomRequest();
            inValue.Body = new YeahTVApi.ServiceProvider.PMSRoomStatusService.SetCleanRoomRequestBody();
            inValue.Body.hotelId = hotelId;
            inValue.Body.roomId = roomId;
            inValue.Body.operatorId = operatorId;
            return ((YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap)(this)).SetCleanRoomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelRoomTypesResponse YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap.GetHotelRoomTypes(YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelRoomTypesRequest request) {
            return base.Channel.GetHotelRoomTypes(request);
        }
        
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomTypeEntity[] GetHotelRoomTypes(string hotelId) {
            YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelRoomTypesRequest inValue = new YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelRoomTypesRequest();
            inValue.Body = new YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelRoomTypesRequestBody();
            inValue.Body.hotelId = hotelId;
            YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelRoomTypesResponse retVal = ((YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap)(this)).GetHotelRoomTypes(inValue);
            return retVal.Body.GetHotelRoomTypesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelRoomTypesResponse> YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap.GetHotelRoomTypesAsync(YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelRoomTypesRequest request) {
            return base.Channel.GetHotelRoomTypesAsync(request);
        }
        
        public System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelRoomTypesResponse> GetHotelRoomTypesAsync(string hotelId) {
            YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelRoomTypesRequest inValue = new YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelRoomTypesRequest();
            inValue.Body = new YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelRoomTypesRequestBody();
            inValue.Body.hotelId = hotelId;
            return ((YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap)(this)).GetHotelRoomTypesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelInfoResponse YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap.GetHotelInfo(YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelInfoRequest request) {
            return base.Channel.GetHotelInfo(request);
        }
        
        public YeahTVApi.ServiceProvider.PMSRoomStatusService.Hall[] GetHotelInfo(string hotelId) {
            YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelInfoRequest inValue = new YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelInfoRequest();
            inValue.Body = new YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelInfoRequestBody();
            inValue.Body.hotelId = hotelId;
            YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelInfoResponse retVal = ((YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap)(this)).GetHotelInfo(inValue);
            return retVal.Body.GetHotelInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelInfoResponse> YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap.GetHotelInfoAsync(YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelInfoRequest request) {
            return base.Channel.GetHotelInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelInfoResponse> GetHotelInfoAsync(string hotelId) {
            YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelInfoRequest inValue = new YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelInfoRequest();
            inValue.Body = new YeahTVApi.ServiceProvider.PMSRoomStatusService.GetHotelInfoRequestBody();
            inValue.Body.hotelId = hotelId;
            return ((YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap)(this)).GetHotelInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YeahTVApi.ServiceProvider.PMSRoomStatusService.SetOOORoomResponse YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap.SetOOORoom(YeahTVApi.ServiceProvider.PMSRoomStatusService.SetOOORoomRequest request) {
            return base.Channel.SetOOORoom(request);
        }
        
        public bool SetOOORoom(string hotelId, string roomId, System.DateTime beginDate, System.DateTime endDate, string reason, string operatorId, out string msg) {
            YeahTVApi.ServiceProvider.PMSRoomStatusService.SetOOORoomRequest inValue = new YeahTVApi.ServiceProvider.PMSRoomStatusService.SetOOORoomRequest();
            inValue.Body = new YeahTVApi.ServiceProvider.PMSRoomStatusService.SetOOORoomRequestBody();
            inValue.Body.hotelId = hotelId;
            inValue.Body.roomId = roomId;
            inValue.Body.beginDate = beginDate;
            inValue.Body.endDate = endDate;
            inValue.Body.reason = reason;
            inValue.Body.operatorId = operatorId;
            YeahTVApi.ServiceProvider.PMSRoomStatusService.SetOOORoomResponse retVal = ((YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap)(this)).SetOOORoom(inValue);
            msg = retVal.Body.msg;
            return retVal.Body.SetOOORoomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMSRoomStatusService.SetOOORoomResponse> YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap.SetOOORoomAsync(YeahTVApi.ServiceProvider.PMSRoomStatusService.SetOOORoomRequest request) {
            return base.Channel.SetOOORoomAsync(request);
        }
        
        public System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMSRoomStatusService.SetOOORoomResponse> SetOOORoomAsync(string hotelId, string roomId, System.DateTime beginDate, System.DateTime endDate, string reason, string operatorId) {
            YeahTVApi.ServiceProvider.PMSRoomStatusService.SetOOORoomRequest inValue = new YeahTVApi.ServiceProvider.PMSRoomStatusService.SetOOORoomRequest();
            inValue.Body = new YeahTVApi.ServiceProvider.PMSRoomStatusService.SetOOORoomRequestBody();
            inValue.Body.hotelId = hotelId;
            inValue.Body.roomId = roomId;
            inValue.Body.beginDate = beginDate;
            inValue.Body.endDate = endDate;
            inValue.Body.reason = reason;
            inValue.Body.operatorId = operatorId;
            return ((YeahTVApi.ServiceProvider.PMSRoomStatusService.RoomStatusModifySoap)(this)).SetOOORoomAsync(inValue);
        }
    }
}
