//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeahTVApi.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class YeahTVApiMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal YeahTVApiMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YeahTVApi.Resource.YeahTVApiMessage", typeof(YeahTVApiMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支付宝(扫码支付).
        /// </summary>
        public static string CommonAlipayQRPay {
            get {
                return ResourceManager.GetString("CommonAlipayQRPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请打开手机或平板上支付宝应用，选择扫一扫，扫描下方二维码.
        /// </summary>
        public static string CommonAlipayQRPayTip {
            get {
                return ResourceManager.GetString("CommonAlipayQRPayTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设备绑定失败.
        /// </summary>
        public static string CommonBindingDeviceFailed {
            get {
                return ResourceManager.GetString("CommonBindingDeviceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设备绑定成功.
        /// </summary>
        public static string CommonBindingDeviceSuccessfully {
            get {
                return ResourceManager.GetString("CommonBindingDeviceSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绑定信息修改成功.
        /// </summary>
        public static string CommonBindingInformationSuccessfully {
            get {
                return ResourceManager.GetString("CommonBindingInformationSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设备已经绑定，可以选择修改绑定信息操作.
        /// </summary>
        public static string CommonBindingSuccessfullyMessage {
            get {
                return ResourceManager.GetString("CommonBindingSuccessfullyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预定失败.
        /// </summary>
        public static string CommonBookingFailed {
            get {
                return ResourceManager.GetString("CommonBookingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调用了启动接口.
        /// </summary>
        public static string CommonBootInterface {
            get {
                return ResourceManager.GetString("CommonBootInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不满足退房条件，无法退房.
        /// </summary>
        public static string CommonCanNotCheckOut {
            get {
                return ResourceManager.GetString("CommonCanNotCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退房失败.
        /// </summary>
        public static string CommonCheckOutFailed {
            get {
                return ResourceManager.GetString("CommonCheckOutFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退房成功.
        /// </summary>
        public static string CommonCheckOutSuccessed {
            get {
                return ResourceManager.GetString("CommonCheckOutSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 续住失败.
        /// </summary>
        public static string CommonContinueLiveFailed {
            get {
                return ResourceManager.GetString("CommonContinueLiveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 续住成功.
        /// </summary>
        public static string CommonContinueLiveSuccessed {
            get {
                return ResourceManager.GetString("CommonContinueLiveSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不存在的设备.
        /// </summary>
        public static string CommonDeviceNotExist {
            get {
                return ResourceManager.GetString("CommonDeviceNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扫码下载华住APP.
        /// </summary>
        public static string CommonDownloadApp {
            get {
                return ResourceManager.GetString("CommonDownloadApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手机号码输入有误，请重新尝试.
        /// </summary>
        public static string CommonErrorInputPhoneNumber {
            get {
                return ResourceManager.GetString("CommonErrorInputPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手机号有误，无法注册.
        /// </summary>
        public static string CommonErrorMobilePhone {
            get {
                return ResourceManager.GetString("CommonErrorMobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入手机号.
        /// </summary>
        public static string CommonInputMobilePhone {
            get {
                return ResourceManager.GetString("CommonInputMobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登陆失败.
        /// </summary>
        public static string CommonLoginFailed {
            get {
                return ResourceManager.GetString("CommonLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手机号不能为空.
        /// </summary>
        public static string CommonMobilePhoneEmpty {
            get {
                return ResourceManager.GetString("CommonMobilePhoneEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 房间尚没有人入住.
        /// </summary>
        public static string CommonNoCheckIn {
            get {
                return ResourceManager.GetString("CommonNoCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无对应房间号.
        /// </summary>
        public static string CommonNoRoomNo {
            get {
                return ResourceManager.GetString("CommonNoRoomNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作超时.
        /// </summary>
        public static string CommonOptionTimeOut {
            get {
                return ResourceManager.GetString("CommonOptionTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  参数错误.
        /// </summary>
        public static string CommonParameterError {
            get {
                return ResourceManager.GetString("CommonParameterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支付失败.
        /// </summary>
        public static string CommonPayFailed {
            get {
                return ResourceManager.GetString("CommonPayFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支付.
        /// </summary>
        public static string CommonPayment {
            get {
                return ResourceManager.GetString("CommonPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册成功，密码已经发送到手机号 {0} 的手机上，请查收..
        /// </summary>
        public static string CommonRegistrationSuccessful {
            get {
                return ResourceManager.GetString("CommonRegistrationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该手机号已是会员,无法重复注册.
        /// </summary>
        public static string CommonRepeatedPhoneNumber {
            get {
                return ResourceManager.GetString("CommonRepeatedPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回.
        /// </summary>
        public static string CommonReturn {
            get {
                return ResourceManager.GetString("CommonReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跳转客房服务首页中....
        /// </summary>
        public static string CommonReturnToSelfServiceHome {
            get {
                return ResourceManager.GetString("CommonReturnToSelfServiceHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无设备绑定信息.
        /// </summary>
        public static string CommonUnknowDeviceBindingInformation {
            get {
                return ResourceManager.GetString("CommonUnknowDeviceBindingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证码错误.
        /// </summary>
        public static string CommonVerificationCodeError {
            get {
                return ResourceManager.GetString("CommonVerificationCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏.
        /// </summary>
        public static string GameTitle {
            get {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 续住房价无法获取.
        /// </summary>
        public static string RommServiceNoStayRoomPrice {
            get {
                return ResourceManager.GetString("RommServiceNoStayRoomPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客房服务.
        /// </summary>
        public static string RoomService {
            get {
                return ResourceManager.GetString("RoomService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欠费.
        /// </summary>
        public static string RoomServiceArrearage {
            get {
                return ResourceManager.GetString("RoomServiceArrearage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退房.
        /// </summary>
        public static string RoomServiceCheckOut {
            get {
                return ResourceManager.GetString("RoomServiceCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票请至前台领取.
        /// </summary>
        public static string RoomServiceCheckOutTip {
            get {
                return ResourceManager.GetString("RoomServiceCheckOutTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每天房价.
        /// </summary>
        public static string RoomServiceDayPrice {
            get {
                return ResourceManager.GetString("RoomServiceDayPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天.
        /// </summary>
        public static string RoomServiceDaysUnit {
            get {
                return ResourceManager.GetString("RoomServiceDaysUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天.
        /// </summary>
        public static string RoomServiceDayUnit {
            get {
                return ResourceManager.GetString("RoomServiceDayUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 续房离店时间.
        /// </summary>
        public static string RoomServiceLastCheckOutTime {
            get {
                return ResourceManager.GetString("RoomServiceLastCheckOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 续住.
        /// </summary>
        public static string RoomServiceStayOver {
            get {
                return ResourceManager.GetString("RoomServiceStayOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请&lt;font style=&apos;color:#ff8048&apos;&gt;打开华住APP&lt;/font&gt;,选择&lt;font style=&apos;color:#ff8048&apos;&gt;扫一扫&lt;/font&gt;,扫描下方&lt;font style=&apos;color:#ff8048&apos;&gt;二维码&lt;/font&gt;.
        /// </summary>
        public static string RoomServiceStayQrTip {
            get {
                return ResourceManager.GetString("RoomServiceStayQrTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 办理续租和退房的前提: &lt;br/&gt;仅限华住会员通过官网或者app渠道预定的入住.
        /// </summary>
        public static string RoomServiceTip {
            get {
                return ResourceManager.GetString("RoomServiceTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总金额.
        /// </summary>
        public static string RoomServiceTotalPrice {
            get {
                return ResourceManager.GetString("RoomServiceTotalPrice", resourceCulture);
            }
        }
    }
}
