//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeahTVApi.ServiceProvider.MemberExtraService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MemberExtraService.IMemberExtraService")]
    public interface IMemberExtraService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberExtraService/DoWork", ReplyAction="http://tempuri.org/IMemberExtraService/DoWorkResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberExtraService/DoWork", ReplyAction="http://tempuri.org/IMemberExtraService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        // CODEGEN: Parameter 'mobile' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberExtraService/IsCheckInByApp", ReplyAction="http://tempuri.org/IMemberExtraService/IsCheckInByAppResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        YeahTVApi.ServiceProvider.MemberExtraService.IsCheckInByAppResponse IsCheckInByApp(YeahTVApi.ServiceProvider.MemberExtraService.IsCheckInByAppRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberExtraService/IsCheckInByApp", ReplyAction="http://tempuri.org/IMemberExtraService/IsCheckInByAppResponse")]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.MemberExtraService.IsCheckInByAppResponse> IsCheckInByAppAsync(YeahTVApi.ServiceProvider.MemberExtraService.IsCheckInByAppRequest request);
        
        // CODEGEN: Parameter 'GetCheckInListByAppResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberExtraService/GetCheckInListByApp", ReplyAction="http://tempuri.org/IMemberExtraService/GetCheckInListByAppResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        YeahTVApi.ServiceProvider.MemberExtraService.GetCheckInListByAppResponse GetCheckInListByApp(YeahTVApi.ServiceProvider.MemberExtraService.GetCheckInListByAppRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberExtraService/GetCheckInListByApp", ReplyAction="http://tempuri.org/IMemberExtraService/GetCheckInListByAppResponse")]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.MemberExtraService.GetCheckInListByAppResponse> GetCheckInListByAppAsync(YeahTVApi.ServiceProvider.MemberExtraService.GetCheckInListByAppRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberExtraService/GetMembers", ReplyAction="http://tempuri.org/IMemberExtraService/GetMembersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        YeahTVApi.ServiceProvider.MemberExtraService.GetMembersResponse GetMembers(YeahTVApi.ServiceProvider.MemberExtraService.GetMembersRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberExtraService/GetMembers", ReplyAction="http://tempuri.org/IMemberExtraService/GetMembersResponse")]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.MemberExtraService.GetMembersResponse> GetMembersAsync(YeahTVApi.ServiceProvider.MemberExtraService.GetMembersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberExtraService/GetMembersByCondition", ReplyAction="http://tempuri.org/IMemberExtraService/GetMembersByConditionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        YeahTVApi.ServiceProvider.MemberExtraService.GetMembersByConditionResponse GetMembersByCondition(YeahTVApi.ServiceProvider.MemberExtraService.GetMembersByConditionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberExtraService/GetMembersByCondition", ReplyAction="http://tempuri.org/IMemberExtraService/GetMembersByConditionResponse")]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.MemberExtraService.GetMembersByConditionResponse> GetMembersByConditionAsync(YeahTVApi.ServiceProvider.MemberExtraService.GetMembersByConditionRequest request);
        
        // CODEGEN: Parameter 'GetMemberRoomdayMsgResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberExtraService/GetMemberRoomdayMsg", ReplyAction="http://tempuri.org/IMemberExtraService/GetMemberRoomdayMsgResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        YeahTVApi.ServiceProvider.MemberExtraService.GetMemberRoomdayMsgResponse GetMemberRoomdayMsg(YeahTVApi.ServiceProvider.MemberExtraService.GetMemberRoomdayMsgRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberExtraService/GetMemberRoomdayMsg", ReplyAction="http://tempuri.org/IMemberExtraService/GetMemberRoomdayMsgResponse")]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.MemberExtraService.GetMemberRoomdayMsgResponse> GetMemberRoomdayMsgAsync(YeahTVApi.ServiceProvider.MemberExtraService.GetMemberRoomdayMsgRequest request);
        
        // CODEGEN: Parameter 'GetMemberUpgradeHistoryResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberExtraService/GetMemberUpgradeHistory", ReplyAction="http://tempuri.org/IMemberExtraService/GetMemberUpgradeHistoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        YeahTVApi.ServiceProvider.MemberExtraService.GetMemberUpgradeHistoryResponse GetMemberUpgradeHistory(YeahTVApi.ServiceProvider.MemberExtraService.GetMemberUpgradeHistoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberExtraService/GetMemberUpgradeHistory", ReplyAction="http://tempuri.org/IMemberExtraService/GetMemberUpgradeHistoryResponse")]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.MemberExtraService.GetMemberUpgradeHistoryResponse> GetMemberUpgradeHistoryAsync(YeahTVApi.ServiceProvider.MemberExtraService.GetMemberUpgradeHistoryRequest request);
        
        // CODEGEN: Parameter 'GetHaoshengyinCardSummaryResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberExtraService/GetHaoshengyinCardSummary", ReplyAction="http://tempuri.org/IMemberExtraService/GetHaoshengyinCardSummaryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        YeahTVApi.ServiceProvider.MemberExtraService.GetHaoshengyinCardSummaryResponse GetHaoshengyinCardSummary(YeahTVApi.ServiceProvider.MemberExtraService.GetHaoshengyinCardSummaryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberExtraService/GetHaoshengyinCardSummary", ReplyAction="http://tempuri.org/IMemberExtraService/GetHaoshengyinCardSummaryResponse")]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.MemberExtraService.GetHaoshengyinCardSummaryResponse> GetHaoshengyinCardSummaryAsync(YeahTVApi.ServiceProvider.MemberExtraService.GetHaoshengyinCardSummaryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsCheckInByApp", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IsCheckInByAppRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mobile;
        
        public IsCheckInByAppRequest() {
        }
        
        public IsCheckInByAppRequest(string mobile) {
            this.mobile = mobile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsCheckInByAppResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IsCheckInByAppResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int IsCheckInByAppResult;
        
        public IsCheckInByAppResponse() {
        }
        
        public IsCheckInByAppResponse(int IsCheckInByAppResult) {
            this.IsCheckInByAppResult = IsCheckInByAppResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCheckInListByApp", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCheckInListByAppRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mobile;
        
        public GetCheckInListByAppRequest() {
        }
        
        public GetCheckInListByAppRequest(string mobile) {
            this.mobile = mobile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCheckInListByAppResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCheckInListByAppResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable GetCheckInListByAppResult;
        
        public GetCheckInListByAppResponse() {
        }
        
        public GetCheckInListByAppResponse(System.Data.DataTable GetCheckInListByAppResult) {
            this.GetCheckInListByAppResult = GetCheckInListByAppResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMembers", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMembersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string memberId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mobile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string memberName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int pageLength;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int currentPage;
        
        public GetMembersRequest() {
        }
        
        public GetMembersRequest(string memberId, string mobile, string memberName, int pageLength, int currentPage) {
            this.memberId = memberId;
            this.mobile = mobile;
            this.memberName = memberName;
            this.pageLength = pageLength;
            this.currentPage = currentPage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMembersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMembersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet GetMembersResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int recordCount;
        
        public GetMembersResponse() {
        }
        
        public GetMembersResponse(System.Data.DataSet GetMembersResult, int recordCount) {
            this.GetMembersResult = GetMembersResult;
            this.recordCount = recordCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMembersByCondition", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMembersByConditionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string condition;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int pageLength;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int currentPage;
        
        public GetMembersByConditionRequest() {
        }
        
        public GetMembersByConditionRequest(string condition, int pageLength, int currentPage) {
            this.condition = condition;
            this.pageLength = pageLength;
            this.currentPage = currentPage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMembersByConditionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMembersByConditionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet GetMembersByConditionResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int recordCount;
        
        public GetMembersByConditionResponse() {
        }
        
        public GetMembersByConditionResponse(System.Data.DataSet GetMembersByConditionResult, int recordCount) {
            this.GetMembersByConditionResult = GetMembersByConditionResult;
            this.recordCount = recordCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMemberRoomdayMsg", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMemberRoomdayMsgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string memberId;
        
        public GetMemberRoomdayMsgRequest() {
        }
        
        public GetMemberRoomdayMsgRequest(string memberId) {
            this.memberId = memberId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMemberRoomdayMsgResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMemberRoomdayMsgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetMemberRoomdayMsgResult;
        
        public GetMemberRoomdayMsgResponse() {
        }
        
        public GetMemberRoomdayMsgResponse(string GetMemberRoomdayMsgResult) {
            this.GetMemberRoomdayMsgResult = GetMemberRoomdayMsgResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Htinns.CRM.BizEntity.Dto")]
    public partial class MemberUpgradeHistoryDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string memberIdField;
        
        private string registerLevelField;
        
        private System.Nullable<System.DateTime> registerTimeField;
        
        private bool registerTimeFieldSpecified;
        
        private UpgradeHistory[] upgradeHistoryListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string MemberId {
            get {
                return this.memberIdField;
            }
            set {
                this.memberIdField = value;
                this.RaisePropertyChanged("MemberId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string RegisterLevel {
            get {
                return this.registerLevelField;
            }
            set {
                this.registerLevelField = value;
                this.RaisePropertyChanged("RegisterLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> RegisterTime {
            get {
                return this.registerTimeField;
            }
            set {
                this.registerTimeField = value;
                this.RaisePropertyChanged("RegisterTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegisterTimeSpecified {
            get {
                return this.registerTimeFieldSpecified;
            }
            set {
                this.registerTimeFieldSpecified = value;
                this.RaisePropertyChanged("RegisterTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=3)]
        public UpgradeHistory[] UpgradeHistoryList {
            get {
                return this.upgradeHistoryListField;
            }
            set {
                this.upgradeHistoryListField = value;
                this.RaisePropertyChanged("UpgradeHistoryList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Htinns.CRM.BizEntity.Dto")]
    public partial class UpgradeHistory : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string memberLevelField;
        
        private System.DateTime upgradeTimeField;
        
        private bool upgradeTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string MemberLevel {
            get {
                return this.memberLevelField;
            }
            set {
                this.memberLevelField = value;
                this.RaisePropertyChanged("MemberLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime UpgradeTime {
            get {
                return this.upgradeTimeField;
            }
            set {
                this.upgradeTimeField = value;
                this.RaisePropertyChanged("UpgradeTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UpgradeTimeSpecified {
            get {
                return this.upgradeTimeFieldSpecified;
            }
            set {
                this.upgradeTimeFieldSpecified = value;
                this.RaisePropertyChanged("UpgradeTimeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Htinns.CRM.BizEntity.Dto")]
    public partial class CardTypeSummaryDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cardTypeField;
        
        private int qtyField;
        
        private bool qtyFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string CardType {
            get {
                return this.cardTypeField;
            }
            set {
                this.cardTypeField = value;
                this.RaisePropertyChanged("CardType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
                this.RaisePropertyChanged("Qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QtySpecified {
            get {
                return this.qtyFieldSpecified;
            }
            set {
                this.qtyFieldSpecified = value;
                this.RaisePropertyChanged("QtySpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMemberUpgradeHistory", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMemberUpgradeHistoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string memberId;
        
        public GetMemberUpgradeHistoryRequest() {
        }
        
        public GetMemberUpgradeHistoryRequest(string memberId) {
            this.memberId = memberId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMemberUpgradeHistoryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMemberUpgradeHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public YeahTVApi.ServiceProvider.MemberExtraService.MemberUpgradeHistoryDto GetMemberUpgradeHistoryResult;
        
        public GetMemberUpgradeHistoryResponse() {
        }
        
        public GetMemberUpgradeHistoryResponse(YeahTVApi.ServiceProvider.MemberExtraService.MemberUpgradeHistoryDto GetMemberUpgradeHistoryResult) {
            this.GetMemberUpgradeHistoryResult = GetMemberUpgradeHistoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHaoshengyinCardSummary", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetHaoshengyinCardSummaryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime beginTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.DateTime endTime;
        
        public GetHaoshengyinCardSummaryRequest() {
        }
        
        public GetHaoshengyinCardSummaryRequest(System.DateTime beginTime, System.DateTime endTime) {
            this.beginTime = beginTime;
            this.endTime = endTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHaoshengyinCardSummaryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetHaoshengyinCardSummaryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Htinns.CRM.BizEntity.Dto")]
        public YeahTVApi.ServiceProvider.MemberExtraService.CardTypeSummaryDto[] GetHaoshengyinCardSummaryResult;
        
        public GetHaoshengyinCardSummaryResponse() {
        }
        
        public GetHaoshengyinCardSummaryResponse(YeahTVApi.ServiceProvider.MemberExtraService.CardTypeSummaryDto[] GetHaoshengyinCardSummaryResult) {
            this.GetHaoshengyinCardSummaryResult = GetHaoshengyinCardSummaryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMemberExtraServiceChannel : YeahTVApi.ServiceProvider.MemberExtraService.IMemberExtraService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MemberExtraServiceClient : System.ServiceModel.ClientBase<YeahTVApi.ServiceProvider.MemberExtraService.IMemberExtraService>, YeahTVApi.ServiceProvider.MemberExtraService.IMemberExtraService {
        
        public MemberExtraServiceClient() {
        }
        
        public MemberExtraServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MemberExtraServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberExtraServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberExtraServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YeahTVApi.ServiceProvider.MemberExtraService.IsCheckInByAppResponse YeahTVApi.ServiceProvider.MemberExtraService.IMemberExtraService.IsCheckInByApp(YeahTVApi.ServiceProvider.MemberExtraService.IsCheckInByAppRequest request) {
            return base.Channel.IsCheckInByApp(request);
        }
        
        public int IsCheckInByApp(string mobile) {
            YeahTVApi.ServiceProvider.MemberExtraService.IsCheckInByAppRequest inValue = new YeahTVApi.ServiceProvider.MemberExtraService.IsCheckInByAppRequest();
            inValue.mobile = mobile;
            YeahTVApi.ServiceProvider.MemberExtraService.IsCheckInByAppResponse retVal = ((YeahTVApi.ServiceProvider.MemberExtraService.IMemberExtraService)(this)).IsCheckInByApp(inValue);
            return retVal.IsCheckInByAppResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.MemberExtraService.IsCheckInByAppResponse> YeahTVApi.ServiceProvider.MemberExtraService.IMemberExtraService.IsCheckInByAppAsync(YeahTVApi.ServiceProvider.MemberExtraService.IsCheckInByAppRequest request) {
            return base.Channel.IsCheckInByAppAsync(request);
        }
        
        public System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.MemberExtraService.IsCheckInByAppResponse> IsCheckInByAppAsync(string mobile) {
            YeahTVApi.ServiceProvider.MemberExtraService.IsCheckInByAppRequest inValue = new YeahTVApi.ServiceProvider.MemberExtraService.IsCheckInByAppRequest();
            inValue.mobile = mobile;
            return ((YeahTVApi.ServiceProvider.MemberExtraService.IMemberExtraService)(this)).IsCheckInByAppAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YeahTVApi.ServiceProvider.MemberExtraService.GetCheckInListByAppResponse YeahTVApi.ServiceProvider.MemberExtraService.IMemberExtraService.GetCheckInListByApp(YeahTVApi.ServiceProvider.MemberExtraService.GetCheckInListByAppRequest request) {
            return base.Channel.GetCheckInListByApp(request);
        }
        
        public System.Data.DataTable GetCheckInListByApp(string mobile) {
            YeahTVApi.ServiceProvider.MemberExtraService.GetCheckInListByAppRequest inValue = new YeahTVApi.ServiceProvider.MemberExtraService.GetCheckInListByAppRequest();
            inValue.mobile = mobile;
            YeahTVApi.ServiceProvider.MemberExtraService.GetCheckInListByAppResponse retVal = ((YeahTVApi.ServiceProvider.MemberExtraService.IMemberExtraService)(this)).GetCheckInListByApp(inValue);
            return retVal.GetCheckInListByAppResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.MemberExtraService.GetCheckInListByAppResponse> YeahTVApi.ServiceProvider.MemberExtraService.IMemberExtraService.GetCheckInListByAppAsync(YeahTVApi.ServiceProvider.MemberExtraService.GetCheckInListByAppRequest request) {
            return base.Channel.GetCheckInListByAppAsync(request);
        }
        
        public System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.MemberExtraService.GetCheckInListByAppResponse> GetCheckInListByAppAsync(string mobile) {
            YeahTVApi.ServiceProvider.MemberExtraService.GetCheckInListByAppRequest inValue = new YeahTVApi.ServiceProvider.MemberExtraService.GetCheckInListByAppRequest();
            inValue.mobile = mobile;
            return ((YeahTVApi.ServiceProvider.MemberExtraService.IMemberExtraService)(this)).GetCheckInListByAppAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YeahTVApi.ServiceProvider.MemberExtraService.GetMembersResponse YeahTVApi.ServiceProvider.MemberExtraService.IMemberExtraService.GetMembers(YeahTVApi.ServiceProvider.MemberExtraService.GetMembersRequest request) {
            return base.Channel.GetMembers(request);
        }
        
        public System.Data.DataSet GetMembers(string memberId, string mobile, string memberName, int pageLength, int currentPage, out int recordCount) {
            YeahTVApi.ServiceProvider.MemberExtraService.GetMembersRequest inValue = new YeahTVApi.ServiceProvider.MemberExtraService.GetMembersRequest();
            inValue.memberId = memberId;
            inValue.mobile = mobile;
            inValue.memberName = memberName;
            inValue.pageLength = pageLength;
            inValue.currentPage = currentPage;
            YeahTVApi.ServiceProvider.MemberExtraService.GetMembersResponse retVal = ((YeahTVApi.ServiceProvider.MemberExtraService.IMemberExtraService)(this)).GetMembers(inValue);
            recordCount = retVal.recordCount;
            return retVal.GetMembersResult;
        }
        
        public System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.MemberExtraService.GetMembersResponse> GetMembersAsync(YeahTVApi.ServiceProvider.MemberExtraService.GetMembersRequest request) {
            return base.Channel.GetMembersAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YeahTVApi.ServiceProvider.MemberExtraService.GetMembersByConditionResponse YeahTVApi.ServiceProvider.MemberExtraService.IMemberExtraService.GetMembersByCondition(YeahTVApi.ServiceProvider.MemberExtraService.GetMembersByConditionRequest request) {
            return base.Channel.GetMembersByCondition(request);
        }
        
        public System.Data.DataSet GetMembersByCondition(string condition, int pageLength, int currentPage, out int recordCount) {
            YeahTVApi.ServiceProvider.MemberExtraService.GetMembersByConditionRequest inValue = new YeahTVApi.ServiceProvider.MemberExtraService.GetMembersByConditionRequest();
            inValue.condition = condition;
            inValue.pageLength = pageLength;
            inValue.currentPage = currentPage;
            YeahTVApi.ServiceProvider.MemberExtraService.GetMembersByConditionResponse retVal = ((YeahTVApi.ServiceProvider.MemberExtraService.IMemberExtraService)(this)).GetMembersByCondition(inValue);
            recordCount = retVal.recordCount;
            return retVal.GetMembersByConditionResult;
        }
        
        public System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.MemberExtraService.GetMembersByConditionResponse> GetMembersByConditionAsync(YeahTVApi.ServiceProvider.MemberExtraService.GetMembersByConditionRequest request) {
            return base.Channel.GetMembersByConditionAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YeahTVApi.ServiceProvider.MemberExtraService.GetMemberRoomdayMsgResponse YeahTVApi.ServiceProvider.MemberExtraService.IMemberExtraService.GetMemberRoomdayMsg(YeahTVApi.ServiceProvider.MemberExtraService.GetMemberRoomdayMsgRequest request) {
            return base.Channel.GetMemberRoomdayMsg(request);
        }
        
        public string GetMemberRoomdayMsg(string memberId) {
            YeahTVApi.ServiceProvider.MemberExtraService.GetMemberRoomdayMsgRequest inValue = new YeahTVApi.ServiceProvider.MemberExtraService.GetMemberRoomdayMsgRequest();
            inValue.memberId = memberId;
            YeahTVApi.ServiceProvider.MemberExtraService.GetMemberRoomdayMsgResponse retVal = ((YeahTVApi.ServiceProvider.MemberExtraService.IMemberExtraService)(this)).GetMemberRoomdayMsg(inValue);
            return retVal.GetMemberRoomdayMsgResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.MemberExtraService.GetMemberRoomdayMsgResponse> YeahTVApi.ServiceProvider.MemberExtraService.IMemberExtraService.GetMemberRoomdayMsgAsync(YeahTVApi.ServiceProvider.MemberExtraService.GetMemberRoomdayMsgRequest request) {
            return base.Channel.GetMemberRoomdayMsgAsync(request);
        }
        
        public System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.MemberExtraService.GetMemberRoomdayMsgResponse> GetMemberRoomdayMsgAsync(string memberId) {
            YeahTVApi.ServiceProvider.MemberExtraService.GetMemberRoomdayMsgRequest inValue = new YeahTVApi.ServiceProvider.MemberExtraService.GetMemberRoomdayMsgRequest();
            inValue.memberId = memberId;
            return ((YeahTVApi.ServiceProvider.MemberExtraService.IMemberExtraService)(this)).GetMemberRoomdayMsgAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YeahTVApi.ServiceProvider.MemberExtraService.GetMemberUpgradeHistoryResponse YeahTVApi.ServiceProvider.MemberExtraService.IMemberExtraService.GetMemberUpgradeHistory(YeahTVApi.ServiceProvider.MemberExtraService.GetMemberUpgradeHistoryRequest request) {
            return base.Channel.GetMemberUpgradeHistory(request);
        }
        
        public YeahTVApi.ServiceProvider.MemberExtraService.MemberUpgradeHistoryDto GetMemberUpgradeHistory(string memberId) {
            YeahTVApi.ServiceProvider.MemberExtraService.GetMemberUpgradeHistoryRequest inValue = new YeahTVApi.ServiceProvider.MemberExtraService.GetMemberUpgradeHistoryRequest();
            inValue.memberId = memberId;
            YeahTVApi.ServiceProvider.MemberExtraService.GetMemberUpgradeHistoryResponse retVal = ((YeahTVApi.ServiceProvider.MemberExtraService.IMemberExtraService)(this)).GetMemberUpgradeHistory(inValue);
            return retVal.GetMemberUpgradeHistoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.MemberExtraService.GetMemberUpgradeHistoryResponse> YeahTVApi.ServiceProvider.MemberExtraService.IMemberExtraService.GetMemberUpgradeHistoryAsync(YeahTVApi.ServiceProvider.MemberExtraService.GetMemberUpgradeHistoryRequest request) {
            return base.Channel.GetMemberUpgradeHistoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.MemberExtraService.GetMemberUpgradeHistoryResponse> GetMemberUpgradeHistoryAsync(string memberId) {
            YeahTVApi.ServiceProvider.MemberExtraService.GetMemberUpgradeHistoryRequest inValue = new YeahTVApi.ServiceProvider.MemberExtraService.GetMemberUpgradeHistoryRequest();
            inValue.memberId = memberId;
            return ((YeahTVApi.ServiceProvider.MemberExtraService.IMemberExtraService)(this)).GetMemberUpgradeHistoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YeahTVApi.ServiceProvider.MemberExtraService.GetHaoshengyinCardSummaryResponse YeahTVApi.ServiceProvider.MemberExtraService.IMemberExtraService.GetHaoshengyinCardSummary(YeahTVApi.ServiceProvider.MemberExtraService.GetHaoshengyinCardSummaryRequest request) {
            return base.Channel.GetHaoshengyinCardSummary(request);
        }
        
        public YeahTVApi.ServiceProvider.MemberExtraService.CardTypeSummaryDto[] GetHaoshengyinCardSummary(System.DateTime beginTime, System.DateTime endTime) {
            YeahTVApi.ServiceProvider.MemberExtraService.GetHaoshengyinCardSummaryRequest inValue = new YeahTVApi.ServiceProvider.MemberExtraService.GetHaoshengyinCardSummaryRequest();
            inValue.beginTime = beginTime;
            inValue.endTime = endTime;
            YeahTVApi.ServiceProvider.MemberExtraService.GetHaoshengyinCardSummaryResponse retVal = ((YeahTVApi.ServiceProvider.MemberExtraService.IMemberExtraService)(this)).GetHaoshengyinCardSummary(inValue);
            return retVal.GetHaoshengyinCardSummaryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.MemberExtraService.GetHaoshengyinCardSummaryResponse> YeahTVApi.ServiceProvider.MemberExtraService.IMemberExtraService.GetHaoshengyinCardSummaryAsync(YeahTVApi.ServiceProvider.MemberExtraService.GetHaoshengyinCardSummaryRequest request) {
            return base.Channel.GetHaoshengyinCardSummaryAsync(request);
        }
        
        public System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.MemberExtraService.GetHaoshengyinCardSummaryResponse> GetHaoshengyinCardSummaryAsync(System.DateTime beginTime, System.DateTime endTime) {
            YeahTVApi.ServiceProvider.MemberExtraService.GetHaoshengyinCardSummaryRequest inValue = new YeahTVApi.ServiceProvider.MemberExtraService.GetHaoshengyinCardSummaryRequest();
            inValue.beginTime = beginTime;
            inValue.endTime = endTime;
            return ((YeahTVApi.ServiceProvider.MemberExtraService.IMemberExtraService)(this)).GetHaoshengyinCardSummaryAsync(inValue);
        }
    }
}
