//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeahTVApi.ServiceProvider.PMS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RcpnSheetDataContract", Namespace="http://schemas.datacontract.org/2004/07/HuaZhu.PMS.Interface.SmartTVService.DataC" +
        "ontract")]
    [System.SerializableAttribute()]
    public partial class RcpnSheetDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CheckInDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CheckOutDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CheckinSrcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CusCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CusNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CusTelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InmateRecIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemberIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecStatusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNo {
            get {
                return this.CardNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNoField, value) != true)) {
                    this.CardNoField = value;
                    this.RaisePropertyChanged("CardNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CheckInDate {
            get {
                return this.CheckInDateField;
            }
            set {
                if ((this.CheckInDateField.Equals(value) != true)) {
                    this.CheckInDateField = value;
                    this.RaisePropertyChanged("CheckInDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CheckOutDate {
            get {
                return this.CheckOutDateField;
            }
            set {
                if ((this.CheckOutDateField.Equals(value) != true)) {
                    this.CheckOutDateField = value;
                    this.RaisePropertyChanged("CheckOutDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheckinSrc {
            get {
                return this.CheckinSrcField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckinSrcField, value) != true)) {
                    this.CheckinSrcField = value;
                    this.RaisePropertyChanged("CheckinSrc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CusCategory {
            get {
                return this.CusCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CusCategoryField, value) != true)) {
                    this.CusCategoryField = value;
                    this.RaisePropertyChanged("CusCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CusName {
            get {
                return this.CusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CusNameField, value) != true)) {
                    this.CusNameField = value;
                    this.RaisePropertyChanged("CusName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CusTel {
            get {
                return this.CusTelField;
            }
            set {
                if ((object.ReferenceEquals(this.CusTelField, value) != true)) {
                    this.CusTelField = value;
                    this.RaisePropertyChanged("CusTel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDType {
            get {
                return this.IDTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.IDTypeField, value) != true)) {
                    this.IDTypeField = value;
                    this.RaisePropertyChanged("IDType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InmateRecID {
            get {
                return this.InmateRecIDField;
            }
            set {
                if ((object.ReferenceEquals(this.InmateRecIDField, value) != true)) {
                    this.InmateRecIDField = value;
                    this.RaisePropertyChanged("InmateRecID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MemberID {
            get {
                return this.MemberIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberIDField, value) != true)) {
                    this.MemberIDField = value;
                    this.RaisePropertyChanged("MemberID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecStatusID {
            get {
                return this.RecStatusIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RecStatusIDField, value) != true)) {
                    this.RecStatusIDField = value;
                    this.RaisePropertyChanged("RecStatusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiveID {
            get {
                return this.ReceiveIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveIDField, value) != true)) {
                    this.ReceiveIDField = value;
                    this.RaisePropertyChanged("ReceiveID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MorningCallDataContract", Namespace="http://schemas.datacontract.org/2004/07/HuaZhu.PMS.Interface.SmartTVService.DataC" +
        "ontract")]
    [System.SerializableAttribute()]
    public partial class MorningCallDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CallTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CusAccIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CusNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InterludeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string McIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ModifyDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperatorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CallTime {
            get {
                return this.CallTimeField;
            }
            set {
                if ((this.CallTimeField.Equals(value) != true)) {
                    this.CallTimeField = value;
                    this.RaisePropertyChanged("CallTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cnt {
            get {
                return this.CntField;
            }
            set {
                if ((this.CntField.Equals(value) != true)) {
                    this.CntField = value;
                    this.RaisePropertyChanged("Cnt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CusAccID {
            get {
                return this.CusAccIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CusAccIDField, value) != true)) {
                    this.CusAccIDField = value;
                    this.RaisePropertyChanged("CusAccID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CusName {
            get {
                return this.CusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CusNameField, value) != true)) {
                    this.CusNameField = value;
                    this.RaisePropertyChanged("CusName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelID {
            get {
                return this.HotelIDField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelIDField, value) != true)) {
                    this.HotelIDField = value;
                    this.RaisePropertyChanged("HotelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Interlude {
            get {
                return this.InterludeField;
            }
            set {
                if ((this.InterludeField.Equals(value) != true)) {
                    this.InterludeField = value;
                    this.RaisePropertyChanged("Interlude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string McID {
            get {
                return this.McIDField;
            }
            set {
                if ((object.ReferenceEquals(this.McIDField, value) != true)) {
                    this.McIDField = value;
                    this.RaisePropertyChanged("McID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Memo {
            get {
                return this.MemoField;
            }
            set {
                if ((object.ReferenceEquals(this.MemoField, value) != true)) {
                    this.MemoField = value;
                    this.RaisePropertyChanged("Memo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifyDate {
            get {
                return this.ModifyDateField;
            }
            set {
                if ((this.ModifyDateField.Equals(value) != true)) {
                    this.ModifyDateField = value;
                    this.RaisePropertyChanged("ModifyDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperatorID {
            get {
                return this.OperatorIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatorIDField, value) != true)) {
                    this.OperatorIDField = value;
                    this.RaisePropertyChanged("OperatorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiveID {
            get {
                return this.ReceiveIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveIDField, value) != true)) {
                    this.ReceiveIDField = value;
                    this.RaisePropertyChanged("ReceiveID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusID {
            get {
                return this.StatusIDField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusIDField, value) != true)) {
                    this.StatusIDField = value;
                    this.RaisePropertyChanged("StatusID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseResultDataContract", Namespace="http://schemas.datacontract.org/2004/07/HuaZhu.PMS.Interface.SmartTVService.DataC" +
        "ontract")]
    [System.SerializableAttribute()]
    public partial class ResponseResultDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrogMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrogMsg {
            get {
                return this.ErrogMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrogMsgField, value) != true)) {
                    this.ErrogMsgField = value;
                    this.RaisePropertyChanged("ErrogMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="V_ProductEntity", Namespace="http://schemas.datacontract.org/2004/07/Htinns.PMS.Entity.GoodsSales")]
    [System.SerializableAttribute()]
    public partial class V_ProductEntity : YeahTVApi.ServiceProvider.PMS.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CostPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DefReceiverTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DiscountPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasInventoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> InventoryQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFixCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSysPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MarketingPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaterialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MnemonicCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NCAccount1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NCAccount2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NCAccount2CostCenterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> ParentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PurchaseLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UOMField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryCode {
            get {
                return this.CategoryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryCodeField, value) != true)) {
                    this.CategoryCodeField = value;
                    this.RaisePropertyChanged("CategoryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CostPrice {
            get {
                return this.CostPriceField;
            }
            set {
                if ((this.CostPriceField.Equals(value) != true)) {
                    this.CostPriceField = value;
                    this.RaisePropertyChanged("CostPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DefReceiverType {
            get {
                return this.DefReceiverTypeField;
            }
            set {
                if ((this.DefReceiverTypeField.Equals(value) != true)) {
                    this.DefReceiverTypeField = value;
                    this.RaisePropertyChanged("DefReceiverType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DiscountPrice {
            get {
                return this.DiscountPriceField;
            }
            set {
                if ((this.DiscountPriceField.Equals(value) != true)) {
                    this.DiscountPriceField = value;
                    this.RaisePropertyChanged("DiscountPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasInventory {
            get {
                return this.HasInventoryField;
            }
            set {
                if ((this.HasInventoryField.Equals(value) != true)) {
                    this.HasInventoryField = value;
                    this.RaisePropertyChanged("HasInventory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelID {
            get {
                return this.HotelIDField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelIDField, value) != true)) {
                    this.HotelIDField = value;
                    this.RaisePropertyChanged("HotelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> InventoryQuantity {
            get {
                return this.InventoryQuantityField;
            }
            set {
                if ((this.InventoryQuantityField.Equals(value) != true)) {
                    this.InventoryQuantityField = value;
                    this.RaisePropertyChanged("InventoryQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFixCost {
            get {
                return this.IsFixCostField;
            }
            set {
                if ((this.IsFixCostField.Equals(value) != true)) {
                    this.IsFixCostField = value;
                    this.RaisePropertyChanged("IsFixCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSysPrice {
            get {
                return this.IsSysPriceField;
            }
            set {
                if ((this.IsSysPriceField.Equals(value) != true)) {
                    this.IsSysPriceField = value;
                    this.RaisePropertyChanged("IsSysPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> MarketingPrice {
            get {
                return this.MarketingPriceField;
            }
            set {
                if ((this.MarketingPriceField.Equals(value) != true)) {
                    this.MarketingPriceField = value;
                    this.RaisePropertyChanged("MarketingPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Material {
            get {
                return this.MaterialField;
            }
            set {
                if ((object.ReferenceEquals(this.MaterialField, value) != true)) {
                    this.MaterialField = value;
                    this.RaisePropertyChanged("Material");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MnemonicCode {
            get {
                return this.MnemonicCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MnemonicCodeField, value) != true)) {
                    this.MnemonicCodeField = value;
                    this.RaisePropertyChanged("MnemonicCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NCAccount1 {
            get {
                return this.NCAccount1Field;
            }
            set {
                if ((object.ReferenceEquals(this.NCAccount1Field, value) != true)) {
                    this.NCAccount1Field = value;
                    this.RaisePropertyChanged("NCAccount1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NCAccount2 {
            get {
                return this.NCAccount2Field;
            }
            set {
                if ((object.ReferenceEquals(this.NCAccount2Field, value) != true)) {
                    this.NCAccount2Field = value;
                    this.RaisePropertyChanged("NCAccount2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NCAccount2CostCenter {
            get {
                return this.NCAccount2CostCenterField;
            }
            set {
                if ((object.ReferenceEquals(this.NCAccount2CostCenterField, value) != true)) {
                    this.NCAccount2CostCenterField = value;
                    this.RaisePropertyChanged("NCAccount2CostCenter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PurchaseLevel {
            get {
                return this.PurchaseLevelField;
            }
            set {
                if ((this.PurchaseLevelField.Equals(value) != true)) {
                    this.PurchaseLevelField = value;
                    this.RaisePropertyChanged("PurchaseLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Spec {
            get {
                return this.SpecField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecField, value) != true)) {
                    this.SpecField = value;
                    this.RaisePropertyChanged("Spec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UOM {
            get {
                return this.UOMField;
            }
            set {
                if ((object.ReferenceEquals(this.UOMField, value) != true)) {
                    this.UOMField = value;
                    this.RaisePropertyChanged("UOM");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityBase", Namespace="http://schemas.datacontract.org/2004/07/Htinns.PMS.Entity.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(YeahTVApi.ServiceProvider.PMS.V_ProductEntity))]
    public partial class EntityBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PMS.IPmsService")]
    public interface IPmsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPmsService/GetRcpnSheetInfoByRoomNo", ReplyAction="http://tempuri.org/IPmsService/GetRcpnSheetInfoByRoomNoResponse")]
        YeahTVApi.ServiceProvider.PMS.RcpnSheetDataContract[] GetRcpnSheetInfoByRoomNo(string hotelID, string roomNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPmsService/GetRcpnSheetInfoByRoomNo", ReplyAction="http://tempuri.org/IPmsService/GetRcpnSheetInfoByRoomNoResponse")]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMS.RcpnSheetDataContract[]> GetRcpnSheetInfoByRoomNoAsync(string hotelID, string roomNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPmsService/GetMorningCallByRoomNo", ReplyAction="http://tempuri.org/IPmsService/GetMorningCallByRoomNoResponse")]
        YeahTVApi.ServiceProvider.PMS.MorningCallDataContract[] GetMorningCallByRoomNo(string hotelID, string roomNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPmsService/GetMorningCallByRoomNo", ReplyAction="http://tempuri.org/IPmsService/GetMorningCallByRoomNoResponse")]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMS.MorningCallDataContract[]> GetMorningCallByRoomNoAsync(string hotelID, string roomNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPmsService/SetMorningCall", ReplyAction="http://tempuri.org/IPmsService/SetMorningCallResponse")]
        YeahTVApi.ServiceProvider.PMS.ResponseResultDataContract SetMorningCall(string hotelID, string roomNo, System.DateTime callTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPmsService/SetMorningCall", ReplyAction="http://tempuri.org/IPmsService/SetMorningCallResponse")]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMS.ResponseResultDataContract> SetMorningCallAsync(string hotelID, string roomNo, System.DateTime callTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPmsService/CancelMorningCall", ReplyAction="http://tempuri.org/IPmsService/CancelMorningCallResponse")]
        int CancelMorningCall(string hotelID, string roomNo, string[] mcIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPmsService/CancelMorningCall", ReplyAction="http://tempuri.org/IPmsService/CancelMorningCallResponse")]
        System.Threading.Tasks.Task<int> CancelMorningCallAsync(string hotelID, string roomNo, string[] mcIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPmsService/GetProductListByHotelId", ReplyAction="http://tempuri.org/IPmsService/GetProductListByHotelIdResponse")]
        YeahTVApi.ServiceProvider.PMS.V_ProductEntity[] GetProductListByHotelId(string hotelID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPmsService/GetProductListByHotelId", ReplyAction="http://tempuri.org/IPmsService/GetProductListByHotelIdResponse")]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMS.V_ProductEntity[]> GetProductListByHotelIdAsync(string hotelID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPmsService/SubmitProductSalesOrder", ReplyAction="http://tempuri.org/IPmsService/SubmitProductSalesOrderResponse")]
        YeahTVApi.ServiceProvider.PMS.SubmitProductSalesOrderResponse SubmitProductSalesOrder(YeahTVApi.ServiceProvider.PMS.SubmitProductSalesOrderRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPmsService/SubmitProductSalesOrder", ReplyAction="http://tempuri.org/IPmsService/SubmitProductSalesOrderResponse")]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMS.SubmitProductSalesOrderResponse> SubmitProductSalesOrderAsync(YeahTVApi.ServiceProvider.PMS.SubmitProductSalesOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPmsService/ChargeRoomAccountByBillId", ReplyAction="http://tempuri.org/IPmsService/ChargeRoomAccountByBillIdResponse")]
        YeahTVApi.ServiceProvider.PMS.ChargeRoomAccountByBillIdResponse ChargeRoomAccountByBillId(YeahTVApi.ServiceProvider.PMS.ChargeRoomAccountByBillIdRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPmsService/ChargeRoomAccountByBillId", ReplyAction="http://tempuri.org/IPmsService/ChargeRoomAccountByBillIdResponse")]
        System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMS.ChargeRoomAccountByBillIdResponse> ChargeRoomAccountByBillIdAsync(YeahTVApi.ServiceProvider.PMS.ChargeRoomAccountByBillIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitProductSalesOrder", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SubmitProductSalesOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string hotelID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string salesDetails;
        
        public SubmitProductSalesOrderRequest() {
        }
        
        public SubmitProductSalesOrderRequest(string hotelID, string salesDetails) {
            this.hotelID = hotelID;
            this.salesDetails = salesDetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitProductSalesOrderResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SubmitProductSalesOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SubmitProductSalesOrderResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string salesOrderNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string errMsg;
        
        public SubmitProductSalesOrderResponse() {
        }
        
        public SubmitProductSalesOrderResponse(bool SubmitProductSalesOrderResult, string salesOrderNo, string errMsg) {
            this.SubmitProductSalesOrderResult = SubmitProductSalesOrderResult;
            this.salesOrderNo = salesOrderNo;
            this.errMsg = errMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChargeRoomAccountByBillId", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChargeRoomAccountByBillIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string salesOrderNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public decimal amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string hotelID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string roomNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string cusName;
        
        public ChargeRoomAccountByBillIdRequest() {
        }
        
        public ChargeRoomAccountByBillIdRequest(string salesOrderNo, decimal amount, string hotelID, string roomNo, string cusName) {
            this.salesOrderNo = salesOrderNo;
            this.amount = amount;
            this.hotelID = hotelID;
            this.roomNo = roomNo;
            this.cusName = cusName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChargeRoomAccountByBillIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChargeRoomAccountByBillIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ChargeRoomAccountByBillIdResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errMsg;
        
        public ChargeRoomAccountByBillIdResponse() {
        }
        
        public ChargeRoomAccountByBillIdResponse(bool ChargeRoomAccountByBillIdResult, string errMsg) {
            this.ChargeRoomAccountByBillIdResult = ChargeRoomAccountByBillIdResult;
            this.errMsg = errMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPmsServiceChannel : YeahTVApi.ServiceProvider.PMS.IPmsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PmsServiceClient : System.ServiceModel.ClientBase<YeahTVApi.ServiceProvider.PMS.IPmsService>, YeahTVApi.ServiceProvider.PMS.IPmsService {
        
        public PmsServiceClient() {
        }
        
        public PmsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PmsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PmsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PmsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public YeahTVApi.ServiceProvider.PMS.RcpnSheetDataContract[] GetRcpnSheetInfoByRoomNo(string hotelID, string roomNo) {
            return base.Channel.GetRcpnSheetInfoByRoomNo(hotelID, roomNo);
        }
        
        public System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMS.RcpnSheetDataContract[]> GetRcpnSheetInfoByRoomNoAsync(string hotelID, string roomNo) {
            return base.Channel.GetRcpnSheetInfoByRoomNoAsync(hotelID, roomNo);
        }
        
        public YeahTVApi.ServiceProvider.PMS.MorningCallDataContract[] GetMorningCallByRoomNo(string hotelID, string roomNo) {
            return base.Channel.GetMorningCallByRoomNo(hotelID, roomNo);
        }
        
        public System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMS.MorningCallDataContract[]> GetMorningCallByRoomNoAsync(string hotelID, string roomNo) {
            return base.Channel.GetMorningCallByRoomNoAsync(hotelID, roomNo);
        }
        
        public YeahTVApi.ServiceProvider.PMS.ResponseResultDataContract SetMorningCall(string hotelID, string roomNo, System.DateTime callTime) {
            return base.Channel.SetMorningCall(hotelID, roomNo, callTime);
        }
        
        public System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMS.ResponseResultDataContract> SetMorningCallAsync(string hotelID, string roomNo, System.DateTime callTime) {
            return base.Channel.SetMorningCallAsync(hotelID, roomNo, callTime);
        }
        
        public int CancelMorningCall(string hotelID, string roomNo, string[] mcIDs) {
            return base.Channel.CancelMorningCall(hotelID, roomNo, mcIDs);
        }
        
        public System.Threading.Tasks.Task<int> CancelMorningCallAsync(string hotelID, string roomNo, string[] mcIDs) {
            return base.Channel.CancelMorningCallAsync(hotelID, roomNo, mcIDs);
        }
        
        public YeahTVApi.ServiceProvider.PMS.V_ProductEntity[] GetProductListByHotelId(string hotelID) {
            return base.Channel.GetProductListByHotelId(hotelID);
        }
        
        public System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMS.V_ProductEntity[]> GetProductListByHotelIdAsync(string hotelID) {
            return base.Channel.GetProductListByHotelIdAsync(hotelID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YeahTVApi.ServiceProvider.PMS.SubmitProductSalesOrderResponse YeahTVApi.ServiceProvider.PMS.IPmsService.SubmitProductSalesOrder(YeahTVApi.ServiceProvider.PMS.SubmitProductSalesOrderRequest request) {
            return base.Channel.SubmitProductSalesOrder(request);
        }
        
        public bool SubmitProductSalesOrder(string hotelID, string salesDetails, out string salesOrderNo, out string errMsg) {
            YeahTVApi.ServiceProvider.PMS.SubmitProductSalesOrderRequest inValue = new YeahTVApi.ServiceProvider.PMS.SubmitProductSalesOrderRequest();
            inValue.hotelID = hotelID;
            inValue.salesDetails = salesDetails;
            YeahTVApi.ServiceProvider.PMS.SubmitProductSalesOrderResponse retVal = ((YeahTVApi.ServiceProvider.PMS.IPmsService)(this)).SubmitProductSalesOrder(inValue);
            salesOrderNo = retVal.salesOrderNo;
            errMsg = retVal.errMsg;
            return retVal.SubmitProductSalesOrderResult;
        }
        
        public System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMS.SubmitProductSalesOrderResponse> SubmitProductSalesOrderAsync(YeahTVApi.ServiceProvider.PMS.SubmitProductSalesOrderRequest request) {
            return base.Channel.SubmitProductSalesOrderAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YeahTVApi.ServiceProvider.PMS.ChargeRoomAccountByBillIdResponse YeahTVApi.ServiceProvider.PMS.IPmsService.ChargeRoomAccountByBillId(YeahTVApi.ServiceProvider.PMS.ChargeRoomAccountByBillIdRequest request) {
            return base.Channel.ChargeRoomAccountByBillId(request);
        }
        
        public bool ChargeRoomAccountByBillId(string salesOrderNo, decimal amount, string hotelID, string roomNo, string cusName, out string errMsg) {
            YeahTVApi.ServiceProvider.PMS.ChargeRoomAccountByBillIdRequest inValue = new YeahTVApi.ServiceProvider.PMS.ChargeRoomAccountByBillIdRequest();
            inValue.salesOrderNo = salesOrderNo;
            inValue.amount = amount;
            inValue.hotelID = hotelID;
            inValue.roomNo = roomNo;
            inValue.cusName = cusName;
            YeahTVApi.ServiceProvider.PMS.ChargeRoomAccountByBillIdResponse retVal = ((YeahTVApi.ServiceProvider.PMS.IPmsService)(this)).ChargeRoomAccountByBillId(inValue);
            errMsg = retVal.errMsg;
            return retVal.ChargeRoomAccountByBillIdResult;
        }
        
        public System.Threading.Tasks.Task<YeahTVApi.ServiceProvider.PMS.ChargeRoomAccountByBillIdResponse> ChargeRoomAccountByBillIdAsync(YeahTVApi.ServiceProvider.PMS.ChargeRoomAccountByBillIdRequest request) {
            return base.Channel.ChargeRoomAccountByBillIdAsync(request);
        }
    }
}
